namespace CCB.AstGenerator;

public static class GeneratorFacts
{
    public const string Namespace = "CCB.AstGenerator";

    public const string SyntaxNamespace = "CCB.Syntax";

    public const string ExtensionsNamespace = "CCB.Extensions";

    public const string SyntaxVisitorNamespace = "CCB.Syntax.Visitor";

    public const string SyntaxVisitorName = "SyntaxVisitor";

    public const string SyntaxInternalNamespace = "CCB.Syntax.Internal";

    public const string SyntaxFactoryNamespace = "CCB.Syntax.Factory";

    public const string SyntaxFactoryName = "SyntaxFactory";

    public const string SyntaxFactoryInternalNamespace = $"{SyntaxFactoryNamespace}.Internal";

    public const string SyntaxFactoryInternalName = "SyntaxFactory";

    public const string SyntaxNodeAttributeName = "SyntaxNodeAttribute";

    public const string SyntaxNodeAttributeFullQualifiedName = $"{Namespace}.{SyntaxNodeAttributeName}";

    public const string SyntaxNodeAttributeCode = $"""
                                              // <auto-generated/>
                                              
                                              namespace {Namespace};
                                              
                                              using System;
                                              
                                              [AttributeUsage(AttributeTargets.Class)]
                                              public class {SyntaxNodeAttributeName} : Attribute;
                                              """;

    public const string NodeSlotAttributeName = "NodeSlotAttribute";

    public const string NodeSlotAttributeFullQualifiedName = $"{Namespace}.{NodeSlotAttributeName}";

    public const string NodeSlotAttributeCode = $$"""
                                                // <auto-generated/>
                                                
                                                namespace {{Namespace}};
                                                
                                                using System;
                                                
                                                [AttributeUsage(AttributeTargets.Property)]
                                                public class {{NodeSlotAttributeName}}(int slot, bool isToken = false, bool isTokenList = false, bool isList = false) : Attribute
                                                {
                                                    public int Slot { get; } = slot;
                                                    
                                                    public bool IsToken { get; } = isToken;
                                                    
                                                    public bool IsTokenList { get; } = isTokenList;
                                                    
                                                    public bool IsList { get; } = isList;
                                                }
                                                """;
}