namespace CCB.Generator;

using System.Collections.Immutable;
using CCB.Generator.Extensions;
using CCB.Generator.Model;
using CCB.Generator.Model.Bounded;
using CCB.Syntax;
using CCB.Syntax.Factory;

internal class CSharpScriptGenerator(IndentedTextWriter writer, GenerateConfig config) : IDisposable
{
    public void WriteTree(BoundTree tree)
    {
        this.WriteFileHeaders();
        this.WriteGlobalProperties(tree.Properties);
        writer.WriteLine();
        this.WriteScriptFunctions(tree);
    }

    private void WriteGlobalProperties(ImmutableArray<BoundPropertyType> properties)
    {
        writer.WriteLine("public static class GlobalProperties");
        writer.OpenBlock();

        foreach (var property in properties)
        {
            writer.WriteLine();
            writer.WriteLine($"public static {property.Model.Type.Name} {property.Model.Name.ToUpperCamelCase()}");
            writer.OpenBlock();
            writer.WriteLine($"get => ScriptFunctions.{property.Getter.Model.Name}();");

            if (property.Setter is not null)
            {
                writer.WriteLine($"set => ScriptFunctions.{property.Setter.Model.Name}(value);");
            }
            writer.CloseBlock();
        }

        writer.CloseBlock();
    }

    private void WriteScriptFunctions(BoundTree tree)
    {
        var globalContext = new GlobalContext(NamespaceType.Global);

        writer.WriteLine("public static class ScriptFunctions");
        writer.OpenBlock();
        this.WriteProperties(tree.Properties, globalContext);
        this.WriteFunctions(tree.Functions, globalContext);
        this.WriteClasses(tree.Classes, globalContext);
        writer.CloseBlock();
    }

    private void WriteClasses(IEnumerable<BoundClassType> classes, TypeContext context)
    {
        foreach (var classType in classes)
        {
            writer.WriteLine();
            this.WriteClass(classType, context);
        }
    }

    private void WriteClass(BoundClassType classType, TypeContext context)
    {
        context = new ClassContext(classType.Model, context.Namespace);

        writer.WriteLine($"public static class {classType.Model.ClassName}Functions");
        writer.OpenBlock();

        this.WriteProperties(classType.Properties, context);
        this.WriteFunctions(classType.Methods, context);
        writer.CloseBlock();
    }

    private void WriteProperties(IEnumerable<BoundPropertyType> properties, TypeContext context)
    {
        foreach (var property in properties)
        {
            writer.WriteLine();
            this.WriteProperty(property, context);
        }
    }

    private void WriteProperty(BoundPropertyType property, TypeContext context)
    {
        this.WriteFunction(property.Getter, context, isHandle: false);

        if (property.Setter is null)
        {
            return;
        }

        writer.WriteLine();
        this.WriteFunction(property.Setter, context, isHandle: false);
    }

    private void WriteFunctions(IEnumerable<BoundFunctionType> functions, TypeContext context)
    {
        foreach (var function in functions)
        {
            writer.WriteLine();
            this.WriteFunction(function, context, isHandle: true);
        }
    }

    private void WriteFunction(BoundFunctionType function, TypeContext context, bool isHandle)
    {
        writer.WriteLine(BuildFunctionDeclaration(function.Model, context, isStatic: true, isUnsafe: true));
        writer.OpenBlock();

        var outs = function.Model.Parameters.Where(parameter => parameter.Type.IsOut).ToList();

        foreach (var outParameter in outs)
        {
            writer.WriteLine($"{outParameter.Name} = default;");
        }

        foreach (var outParameter in outs)
        {
            writer.WriteLine($"fixed ({outParameter.Type.Name}* {outParameter.Name}Ptr = &{outParameter.Name})");
        }

        writer.OpenBlock();
        writer.WriteLine("var result = ExecuteContext");
        writer.Indent();
        writer.WriteLine($".FromDeclaration(\"{function.Declaration}\")");

        var parameters = GetParametersWithThis(function.Model.Parameters, context);
        var i = 0;

        foreach (var parameter in parameters)
        {
            var name = parameter.Type.IsOut ? $"(IntPtr){parameter.Name}Ptr" : parameter.Name;

            writer.WriteLine($".WithArgument({i}, {name})");

            i++;
        }

        writer.WriteLine(".Execute();");
        writer.Unindent();

        if (function.Model.ReturnType.Kind != SyntaxKind.Void)
        {
            writer.WriteLine($"return result.{GetReturnMethod(function.Model.ReturnType, isHandle)}();");
        }

        writer.CloseBlock();

        writer.CloseBlock();
    }

    private void WriteFileHeaders()
    {
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("namespace CCB.Internal;");
        writer.WriteLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Runtime.InteropServices;");
        writer.WriteLine("using System.Collections;");
        writer.WriteLine();
    }

    private static string BuildFunctionDeclaration(FunctionType function, TypeContext context, bool isStatic, bool isUnsafe)
    {
        var parameters = BuildDeclarationParameterList(function, context);
        var staticModifier = isStatic ? "static " : string.Empty;
        var unsafeModifier = isUnsafe ? "unsafe " : string.Empty;
        return $"public {staticModifier}{unsafeModifier}{GetReturnTypeText(function.ReturnType)} {function.Name}({parameters})";
    }

    private static string BuildDeclarationParameterList(FunctionType function, TypeContext context)
    {
        var parameterTexts = function.Parameters.Select(GetParameterText);
        return JoinWithThis(parameterTexts, context, GetThisParameterText);
    }

    private static IEnumerable<ParameterType> GetParametersWithThis(IEnumerable<ParameterType> parameters, TypeContext context) => context switch
    {
        GlobalContext => parameters,
        ClassContext classContext => parameters.Prepend(new ParameterType("@this",
            new ValueType(
                classContext.Type.ClassName,
                SyntaxKind.Identifier,
                SyntaxToken.None,
                SyntaxFactory.Token(SyntaxKind.In)),
            null)),
        _ => throw new ArgumentOutOfRangeException(nameof(context)),
    };

    private static string JoinWithThis(IEnumerable<string> texts, TypeContext context, Func<ClassType, string> thisTextProvider)
    {
        var allTexts = context switch
        {
            GlobalContext => texts,
            ClassContext classContext => texts.Prepend(thisTextProvider(classContext.Type)),
            _ => throw new ArgumentOutOfRangeException(nameof(context)),
        };
        return CommaJoin(allTexts);
    }

    private static string CommaJoin(IEnumerable<string?> values)
    {
        return string.Join(", ", values);
    }

    private static string GetParameterText(ParameterType parameter) =>
        $"{GetTypeModifiersText(parameter.Type)}{GetParameterTypeText(parameter.Type)} {parameter.Name}";

    private static string GetThisParameterText(ClassType classType) => $"{classType.ClassName} @this";

    private static string GetReturnMethod(ValueType type, bool isHandle) => type.Kind switch
    {
        SyntaxKind.QuestionMark => "GetPointer",
        SyntaxKind.Ref => "GetPointer",
        SyntaxKind.Bool => "GetBool",
        SyntaxKind.Int8 => "GetByte",
        SyntaxKind.Int16 => "GetShort",
        SyntaxKind.Int => "GetInt",
        SyntaxKind.UInt => "GetUInt",
        SyntaxKind.Int64 => "GetLong",
        SyntaxKind.Float => "GetFloat",
        SyntaxKind.String => "GetString",
        _ => isHandle ? $"GetRefObject<{type.Name}>" : $"GetObject<{type.Name}>",
    };

    private static string GetReturnTypeText(ValueType type) => type.Kind switch
    {
        SyntaxKind.QuestionMark => "IntPtr",
        SyntaxKind.Ref => "in IntPtr",
        SyntaxKind.Int8 => "byte",
        SyntaxKind.Int16 => "short",
        SyntaxKind.UInt => "uint",
        SyntaxKind.Int64 => "long",
        _ => GetTypeText(type),
    };

    private static string GetParameterTypeText(ValueType type) => type.Kind switch
    {
        SyntaxKind.QuestionMark => "IntPtr",
        SyntaxKind.Ref => "IntPtr",
        SyntaxKind.Int8 => "byte",
        SyntaxKind.Int16 => "short",
        SyntaxKind.UInt => "uint",
        SyntaxKind.Int64 => "long",
        _ => GetTypeText(type),
    };

    private static string GetTypeText(ValueType type)
    {
        return type.IsHandle ? "IntPtr" : type.Name;
    }

    private static string GetTypeModifiersText(ValueType type)
    {
        var tokens = new[] { type.RefHandleToken, type.InoutToken };
        var modifierTexts = tokens
            .Where(token => token.Kind is not SyntaxKind.None and not SyntaxKind.Ampersand)
            .Select(GetModifierText)
            .ToList();

        return modifierTexts.Count > 0
            ? string.Join(' ', modifierTexts) + " "
            : string.Empty;
    }

    private static string GetModifierText(SyntaxToken token) => token.Kind switch
    {
        SyntaxKind.In => "in",
        SyntaxKind.Out => "out",
        SyntaxKind.Handle => string.Empty,
        _ => throw new ArgumentOutOfRangeException(nameof(token)),
    };

    public void Dispose()
    {
        writer.Dispose();
    }
}

internal class CSharpClassGenerator(IndentedTextWriter writer, GenerateConfig config) : IDisposable
{
    public void WriteClass(BoundClassType classType)
    {
        this.WriteFileHeaders();

        writer.WriteLine($"public struct {classType.Model.ClassName}(ObjectHandle handle) : IScriptObject");
        writer.OpenBlock();
        writer.WriteLine("public ObjectHandle Handle { get; } = handle;");
        this.WriteIterator(classType);

        writer.WriteLine();
        writer.WriteLine("public static IScriptObject Create(ObjectHandle handle)");
        writer.OpenBlock();
        writer.WriteLine($"return new {classType.Model.ClassName}(handle);");
        writer.CloseBlock();

        foreach (var property in classType.Properties)
        {
            writer.WriteLine();
            writer.WriteLine($"public {property.Model.Type.Name} {property.Model.Name}");
            writer.OpenBlock();
            writer.WriteLine($"get => ScriptFunctions.{classType.Model.ClassName}Functions.{property.Getter.Model.Name}(this);");

            if (property.Setter is not null)
            {
                writer.WriteLine($"set => ScriptFunctions.{classType.Model.ClassName}Functions.{property.Setter.Model.Name}(this, value);");
            }

            writer.CloseBlock();
        }

        foreach (var function in classType.Methods)
        {
            writer.WriteLine();
            writer.WriteLine(BuildFunctionDeclaration(function.Model));
            writer.OpenBlock();
            writer.WriteLine(BuildFunctionBody(classType.Model, function.Model));
            writer.CloseBlock();
        }

        writer.CloseBlock();
    }

    private void WriteIterator(BoundClassType classType)
    {
        var iteratorType = classType.Iterator;

        if (iteratorType is null)
        {
            return;
        }

        var className = classType.Model.ClassName;

        writer.WriteLine();
        writer.WriteLine($"public struct Iterator(IteratorOpaque opaque) : IEnumerator<{className}>");
        writer.OpenBlock();

        writer.WriteLine("private IteratorOpaque _opaque = opaque;");
        writer.WriteLine($"private {className}? _current;");
        writer.WriteLine($"public {className} Current => this._current!.Value;");
        writer.WriteLine("object IEnumerator.Current => this._current!.Value;");
        writer.WriteLine();
        writer.WriteLine("public static Iterator Create()");
        writer.OpenBlock();
        writer.WriteLine($"return new Iterator(IteratorOpaque.Create(\"{iteratorType.CreateIteratorFunction.Declaration}\"));");
        writer.CloseBlock();

        writer.WriteLine();

        writer.WriteLine("public bool MoveNext()");
        writer.OpenBlock();
        writer.WriteLine($"if (this._opaque.IsNull(\"{iteratorType.IteratorIsNullFunction.Declaration}\"))");
        writer.OpenBlock();
        writer.WriteLine("this._current = null;");
        writer.WriteLine("return false;");
        writer.CloseBlock();
        writer.WriteLine();
        writer.WriteLine($"this._current = this._opaque.Get<{className}>(\"{iteratorType.IteratorGetFunction.Declaration}\");");
        writer.WriteLine($"this._opaque.Advance(\"{iteratorType.IteratorAdvanceFunction.Declaration}\");");
        writer.WriteLine();
        writer.WriteLine("return true;");
        writer.CloseBlock();

        writer.WriteLine();

        writer.WriteLine("public void Reset()");
        writer.OpenBlock();
        writer.WriteLine("throw new NotSupportedException();");
        writer.CloseBlock();

        writer.WriteLine();

        writer.WriteLine("public void Dispose()");
        writer.OpenBlock();
        writer.CloseBlock();

        writer.CloseBlock();

        writer.WriteLine();

        writer.WriteLine($"public class IteratorEnumerable : IEnumerable<{className}>");
        writer.OpenBlock();
        writer.WriteLine("public Iterator GetEnumerator() => Iterator.Create();");
        writer.WriteLine();
        writer.WriteLine($"IEnumerator<{className}> IEnumerable<{className}>.GetEnumerator() => this.GetEnumerator();");
        writer.WriteLine();
        writer.WriteLine("IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();");
        writer.CloseBlock();

        writer.WriteLine();

        writer.WriteLine("public static IteratorEnumerable List()");
        writer.OpenBlock();
        writer.WriteLine("return new IteratorEnumerable();");
        writer.CloseBlock();
    }

    private void WriteFileHeaders()
    {
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("namespace CCB.Internal;");
        writer.WriteLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Runtime.InteropServices;");
        writer.WriteLine("using System.Collections;");
        writer.WriteLine();
    }

    private static string BuildFunctionDeclaration(FunctionType function)
    {
        var parameters = BuildDeclarationParameterList(function);
        return $"public {GetReturnTypeText(function.ReturnType)} {function.Name}({parameters})";
    }

    private static string BuildDeclarationParameterList(FunctionType function)
    {
        var parameterTexts = function.Parameters.Select(GetParameterText);
        return CommaJoin(parameterTexts);
    }

    private static string BuildFunctionBody(ClassType classType, FunctionType function)
    {
        var call = $"ScriptFunctions.{classType.ClassName}Functions.{function.Name}({BuildArgumentList(function)})";

        return function.ReturnType.Kind is SyntaxKind.Void ? $"{call};" : $"return {call};";
    }

    private static string BuildArgumentList(FunctionType function)
    {
        var argumentTexts = function.Parameters.Select(GetArgumentText);
        return JoinWithThis(argumentTexts);
    }

    private static string JoinWithThis(IEnumerable<string> texts)
    {
        return CommaJoin(texts.Prepend("this"));
    }

    private static string CommaJoin(IEnumerable<string?> values)
    {
        return string.Join(", ", values);
    }

    private static string GetArgumentText(ParameterType parameter) =>
        parameter.Type.IsHandle ? parameter.Name : $"{GetTypeModifiersText(parameter.Type)}{parameter.Name}";

    private static string GetParameterText(ParameterType parameter) =>
        $"{GetTypeModifiersText(parameter.Type)}{GetParameterTypeText(parameter.Type)} {parameter.Name}";

    private static string GetReturnTypeText(ValueType type) => type.Kind switch
    {
        SyntaxKind.QuestionMark => "IntPtr",
        SyntaxKind.Ref => "IntPtr",
        SyntaxKind.Int8 => "byte",
        SyntaxKind.Int16 => "short",
        SyntaxKind.UInt => "uint",
        SyntaxKind.Int64 => "long",
        _ => GetTypeText(type),
    };

    private static string GetParameterTypeText(ValueType type) => type.Kind switch
    {
        SyntaxKind.QuestionMark => "IntPtr",
        SyntaxKind.Ref => "IntPtr",
        SyntaxKind.Int8 => "byte",
        SyntaxKind.Int16 => "short",
        SyntaxKind.UInt => "uint",
        SyntaxKind.Int64 => "long",
        _ => GetTypeText(type),
    };

    private static string GetTypeText(ValueType type)
    {
        return type.IsHandle ? "IntPtr" : type.Name;
    }

    private static string GetTypeModifiersText(ValueType type)
    {
        var tokens = new[] { type.RefHandleToken, type.InoutToken };
        var modifierTexts = tokens
            .Where(token => token.Kind is not SyntaxKind.None and not SyntaxKind.Ampersand)
            .Select(GetModifierText)
            .ToList();

        return modifierTexts.Count > 0
            ? string.Join(' ', modifierTexts) + " "
            : string.Empty;
    }

    private static string GetModifierText(SyntaxToken token) => token.Kind switch
    {
        SyntaxKind.In => "in",
        SyntaxKind.Out => "out",
        SyntaxKind.Handle => "ref",
        _ => throw new ArgumentOutOfRangeException(nameof(token)),
    };

    public void Dispose()
    {
        writer.Dispose();
    }
}