namespace CCB.Generator;

using System.Collections;
using System.Collections.Immutable;
using CCB.Extensions;
using CCB.Generator.Extensions;
using CCB.Syntax;
using CCB.Syntax.Visitor;

internal class CSharpScriptGenerator(IndentedTextWriter writer, GeneratorContext context) : SimpleVisitor
{
    private readonly ScriptFunctionsGenerator _scriptFunctionsGenerator = new ScriptFunctionsGenerator(writer, context);

    public override void VisitRoot(RootSyntax root)
    {
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine();
        writer.WriteLine("namespace CCB.Internal;");
        writer.WriteLine();
        writer.WriteLine("using System.Diagnostics;");
        writer.WriteLine("using System.Runtime.InteropServices;");
        writer.WriteLine("using System.Collections;");
        writer.WriteLine();

        root.Accept(this._scriptFunctionsGenerator);

        for (var i = 0; i < root.Members.Count; i++)
        {
            var member = root.Members[i];

            if (i > 0 && member is ClassDeclarationSyntax)
            {
                writer.WriteLine();
            }

            member.Accept(this);
        }
    }

    public override void VisitGlobalProperty(GlobalPropertySyntax node)
    {
        var propertyName = node.Identifier.Text;
        var propertyType = node.Type.Identifier.Text;

        writer.WriteLine("public static partial class GlobalProperties");
        writer.WriteLine("{");

        using (writer.Indent())
        {
            writer.WriteLine($"public static {propertyType} {propertyName.ToUpperCamelCase()}");
            writer.WriteLine("{");

            using (writer.Indent())
            {
                writer.WriteLine($"get => {GeneratorFacts.ScriptFunctionsName}.Get{propertyName}();");
            }

            writer.WriteLine("}");
        }

        writer.WriteLine("}");
    }

    public override void VisitClassDeclaration(ClassDeclarationSyntax node)
    {
        var className = node.Identifier.Text;

        var isIterable = context.Config.Iterables.Contains(className);

        writer.WriteLine($"public struct {className}(ObjectHandle handle) : IScriptObject");

        writer.WriteLine("{");

        using (writer.Indent())
        {
            //writer.WriteLine(context.Config.InternalClasses.Contains(className)
            //    ? "[StructLayout(LayoutKind.Sequential, Size = 4)]"
            //    : "[StructLayout(LayoutKind.Sequential)]");

            //writer.WriteLine("private readonly struct Opaque");
            //writer.WriteLine("{");

            //using (writer.Indent())
            //{
            //    // TODO Fields
            //}

            //writer.WriteLine("}");

            //writer.WriteLine();

            writer.WriteLine("public ObjectHandle Handle { get; } = handle;");
            writer.WriteLine();
            writer.WriteLine("public static IScriptObject Create(ObjectHandle handle)");
            writer.WriteLine("{");

            using (writer.Indent())
            {
                writer.WriteLine($"return new {className}(handle);");
            }

            writer.WriteLine("}");

            WriteIterator();

            writer.WriteLine();

            for (var i = 0; i < node.Members.Count; i++)
            {
                if (i > 0)
                {
                    writer.WriteLine();
                }

                var member = node.Members[i];
                member.Accept(this);
            }
        }

        writer.WriteLine("}");

        return;

        void WriteIterator()
        {
            var iterables = context.Config.Iterables;

            if (!iterables.Contains(className))
            {
                return;
            }

            var iteratorName = $"{className}Iterator";

            writer.WriteLine();
            writer.WriteLine($"public struct Iterator(IteratorOpaque opaque) : IEnumerator<{className}>");
            writer.WriteLine("{");

            using (writer.Indent())
            {
                writer.WriteLine("private IteratorOpaque _opaque = opaque;");
                writer.WriteLine($"private {className}? _current;");
                writer.WriteLine($"public {className} Current => this._current!.Value;");
                writer.WriteLine("object IEnumerator.Current => this._current!.Value;");

                writer.WriteLine();

                writer.WriteLine("public static Iterator Create()");
                writer.WriteLine("{");

                using (writer.Indent())
                {
                    GeneratorFacts.GenerateInvokeCode(writer, [], $"{iteratorName} ccb::_{className}::create_iterator()");
                    writer.WriteLine($"var handle = {GeneratorFacts.NativeBindingsName}.GetModuleReturnObject({GeneratorFacts.ScriptFunctionsName}.{GeneratorFacts.ModuleHandleName});");
                    writer.WriteLine("var opaque = IteratorOpaque.Create(handle);");
                    writer.WriteLine("return new Iterator(opaque);");
                }

                writer.WriteLine("}");

                writer.WriteLine();

                writer.WriteLine("public bool MoveNext()");
                writer.WriteLine("{");

                using (writer.Indent())
                {
                    writer.WriteLine("if (this.IsNull())");
                    writer.WriteLine("{");

                    using (writer.Indent())
                    {
                        writer.WriteLine("this._current = null;");
                        writer.WriteLine("return false;");
                    }

                    writer.WriteLine("}");

                    writer.WriteLine("this._current = this.Get();");
                    writer.WriteLine("this.Advance();");
                    writer.WriteLine();
                    writer.WriteLine("return true;");
                }

                writer.WriteLine("}");

                writer.WriteLine();

                writer.WriteLine("public void Reset()");
                writer.WriteLine("{");

                using (writer.Indent())
                {
                    writer.WriteLine("throw new NotSupportedException();");
                }

                writer.WriteLine("}");

                writer.WriteLine();

                writer.WriteLine("public void Dispose()");
                writer.WriteLine("{");
                writer.WriteLine("}");

                writer.WriteLine();

                writer.WriteLine($"public unsafe {className} Get()");
                writer.WriteLine("{");

                using (writer.Indent())
                {
                    writer.WriteLine("fixed (IteratorOpaque* ptr = &this._opaque)");
                    writer.WriteLine("{");

                    using (writer.Indent())
                    {
                        writer.WriteLine("var nPtr = (IntPtr)ptr;");

                        GeneratorFacts.GenerateInvokeCode(writer,
                            [("nPtr", string.Empty, SyntaxKind.Ref)],
                            $"{className} ccb::_{className}::iterator_get({iteratorName}& in)",
                            SyntaxKind.Identifier,
                            className,
                            false);
                    }

                    writer.WriteLine("}");
                }

                writer.WriteLine("}");

                writer.WriteLine();

                writer.WriteLine("public unsafe void Advance()");
                writer.WriteLine("{");

                using (writer.Indent())
                {
                    writer.WriteLine("fixed (IteratorOpaque* ptr = &this._opaque)");
                    writer.WriteLine("{");

                    using (writer.Indent())
                    {
                        writer.WriteLine("var nPtr = (IntPtr)ptr;");

                        GeneratorFacts.GenerateInvokeCode(writer,
                            [("nPtr", string.Empty, SyntaxKind.Ref)],
                            $"void ccb::_{className}::iterator_advance({iteratorName}& in)");
                    }

                    writer.WriteLine("}");
                }

                writer.WriteLine("}");

                writer.WriteLine();

                writer.WriteLine("public unsafe bool IsNull()");
                writer.WriteLine("{");

                using (writer.Indent())
                {
                    writer.WriteLine("fixed (IteratorOpaque* ptr = &this._opaque)");
                    writer.WriteLine("{");

                    using (writer.Indent())
                    {
                        writer.WriteLine("var nPtr = (IntPtr)ptr;");

                        GeneratorFacts.GenerateInvokeCode(writer,
                            [("nPtr", string.Empty, SyntaxKind.Ref)],
                            $"bool ccb::_{className}::iterator_is_null({iteratorName}& in)",
                            SyntaxKind.Bool,
                            string.Empty,
                            false);
                    }

                    writer.WriteLine("}");
                }

                writer.WriteLine("}");
            }

            writer.WriteLine("}");

            writer.WriteLine();

            writer.WriteLine($"public class IteratorEnumerable : IEnumerable<{className}>");
            writer.WriteLine("{");

            using (writer.Indent())
            {
                writer.WriteLine("public Iterator GetEnumerator() => Iterator.Create();");
                writer.WriteLine();
                writer.WriteLine($"IEnumerator<{className}> IEnumerable<{className}>.GetEnumerator() => this.GetEnumerator();");
                writer.WriteLine();
                writer.WriteLine("IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();");
            }

            writer.WriteLine("}");

            writer.WriteLine();

            writer.WriteLine("public static IteratorEnumerable List()");
            writer.WriteLine("{");

            using (writer.Indent())
            {
                writer.WriteLine("return new IteratorEnumerable();");
            }

            writer.WriteLine("}");
        }
    }

    public override void VisitMethodDeclaration(MethodDeclarationSyntax node)
    {
        var className = ((ClassDeclarationSyntax)node.Parent!).Identifier.Text;

        var methodName = node.Identifier.Text;

        if (node.ParameterList.Parameters.Any(parameter => context.Config.FuncDefs.Any(d => d.DefName == parameter.Element.Type.Identifier.Text)))
        {
            // TODO FuncDef fix
            return;
        }

        var parameters = node.ParameterList.Parameters
            .Select((p, i) =>
            {
                var element = p.Element;
                var typeName = GeneratorFacts.GetCSharpTypeName(element.Type);
                var identifierName = element.Identifier.Kind == SyntaxKind.None
                    ? $"unnamed{i}"
                    : element.Identifier.Text;

                return $"{typeName} {identifierName}";
            });

        var parametersText = string.Join(", ", parameters);

        var argumentsWithThis = node.ParameterList.Parameters
            .Select((p, i) =>
            {
                var element = p.Element;
                var outText = element.Type.Inout.Kind == SyntaxKind.Out ? "out " : string.Empty;
                var identifier = element.Identifier.Kind == SyntaxKind.None ? $"unnamed{i}" : element.Identifier.Text;

                return $"{outText}{identifier}";
            })
            .Prepend("this");

        var argumentsWithThisText = string.Join(", ", argumentsWithThis);

        writer.WriteLine($"public {node.ReturnType.Identifier.Text} {methodName}({parametersText})");
        writer.WriteLine("{");

        using (writer.Indent())
        {
            writer.WriteLine(node.ReturnType.IsVoid
                ? $"{GeneratorFacts.ScriptFunctionsName}.As{className}.{methodName}({argumentsWithThisText});"
                : $"return {GeneratorFacts.ScriptFunctionsName}.As{className}.{methodName}({argumentsWithThisText});");
        }

        writer.WriteLine("}");
    }

    public override void VisitFieldDeclaration(FieldDeclarationSyntax node)
    {
        var className = ((ClassDeclarationSyntax)node.Parent!).Identifier.Text;
        var propertyName = node.Identifier.Text;
        var propertyType = node.Type.Identifier.Text;

        writer.WriteLine($"public {propertyType} {propertyName}");
        writer.WriteLine("{");

        using (writer.Indent())
        {
            writer.WriteLine($"get => {GeneratorFacts.ScriptFunctionsName}.As{className}.Get{propertyName}(this);");

            if (!node.Modifiers.Any(SyntaxKind.Const))
            {
                writer.WriteLine($"set => {GeneratorFacts.ScriptFunctionsName}.As{className}.Set{propertyName}(this, value);");
            }
        }

        writer.WriteLine("}");
    }
}

internal class ScriptFunctionsGenerator(IndentedTextWriter writer, GeneratorContext context) : SimpleVisitor
{
    public override void VisitRoot(RootSyntax root)
    {
        writer.WriteLine("public static class ScriptFunctions");
        writer.WriteLine("{");

        using (writer.Indent())
        {
            writer.WriteLine($"public static ModuleHandle {GeneratorFacts.ModuleHandleName} {{ get; internal set; }}");

            foreach (var member in root.Members)
            {
                writer.WriteLine();

                member.Accept(this);
            }
        }

        writer.WriteLine("}");
    }

    public override void VisitGlobalProperty(GlobalPropertySyntax node)
    {
        var propertyName = node.Identifier.Text;
        var propertyType = node.Type.Identifier.Text;

        GenerateGet();

        return;

        void GenerateGet()
        {
            writer.WriteLine($"public static unsafe {propertyType} Get{propertyName}()");
            writer.WriteLine("{");

            using (writer.Indent())
            {
                GeneratorFacts.GenerateInvokeCode(writer,
                    [],
                    $"{propertyType} ccb::Get{propertyName}()",
                    node.Type.Kind,
                    node.Type.Identifier.Text,
                    false);
            }

            writer.WriteLine("}");
        }
    }

    public override void VisitFunctionDeclaration(FunctionDeclarationSyntax node)
    {
        var methodName = node.Identifier.Text;

        var parameters = node.ParameterList.Parameters
            .Select((p, i) =>
            {
                var element = p.Element;
                var typeName = GeneratorFacts.GetCSharpTypeName(element.Type);
                var identifierName = element.Identifier.Kind == SyntaxKind.None
                    ? $"unnamed{i}"
                    : element.Identifier.Text;

                var hasFuncDef = context.Config.FuncDefs.Any(d => d.DefName == element.Type.Identifier.Text);

                return (
                    TypeKind: element.Type.Kind,
                    TypeName: typeName,
                    Out: element.Type.Inout.Kind == SyntaxKind.Out ? "out " : string.Empty,
                    IdentifierName: identifierName,
                    HasFuncDef: hasFuncDef
                );
            }).ToImmutableArray();

        if (parameters.Any(p => p.HasFuncDef))
        {
            // TODO FuncDef fix
            return;
        }

        var parametersText = string.Join(", ", parameters.Select(p => $"{p.TypeName} {p.IdentifierName}"));

        var declarationReturnTypeName = node.ReturnType.Identifier.Kind == SyntaxKind.String
            ? "char"
            : node.ReturnType.ToStructuredString();

        var declarationParameters = node.ParameterList.Parameters
            .Select(p =>
            {
                var element = p.Element;

                var typeName = element.Type.Identifier.Kind == SyntaxKind.String
                    ? "const char"
                    :element.Type.ToStructuredString();

                var identifierName = element.Identifier.Text;

                return $"{typeName} {identifierName}";
            });

        var declarationParametersText = string.Join(", ", declarationParameters);

        var declaration = $"{declarationReturnTypeName} ccb::{methodName}({declarationParametersText})";

        writer.WriteLine($"public static unsafe {GeneratorFacts.GetCSharpTypeName(node.ReturnType, false)} {methodName}({parametersText})");
        writer.WriteLine("{");

        using (writer.Indent())
        {
            GeneratorFacts.GenerateInvokeCode(writer,
                [.. parameters.Select(p => (p.IdentifierName, p.Out, p.TypeKind))],
                declaration,
                node.ReturnType.Kind,
                node.ReturnType.Identifier.Text,
                true);
        }

        writer.WriteLine("}");
    }

    public override void VisitClassDeclaration(ClassDeclarationSyntax node)
    {
        var className = node.Identifier.Text;

        writer.WriteLine($"public static class As{className}");
        writer.WriteLine("{");

        using (writer.Indent())
        {
            for (var i = 0; i < node.Members.Count; i++)
            {
                if (i > 0)
                {
                    writer.WriteLine();
                }

                var member = node.Members[i];
                member.Accept(this);
            }
        }

        writer.WriteLine("}");
    }

    public override void VisitMethodDeclaration(MethodDeclarationSyntax node)
    {
        var className = ((ClassDeclarationSyntax)node.Parent!).Identifier.Text;

        var methodName = node.Identifier.Text;

        var parametersWithThis = node.ParameterList.Parameters
            .Select((p, i) =>
            {
                var element = p.Element;
                var typeName = GeneratorFacts.GetCSharpTypeName(element.Type);
                var identifierName = element.Identifier.Kind == SyntaxKind.None
                    ? $"unnamed{i}"
                    : element.Identifier.Text;

                var hasFuncDef = context.Config.FuncDefs.Any(d => d.DefName == element.Type.Identifier.Text);

                return (
                    TypeKind: element.Type.Kind,
                    TypeName: typeName,
                    Out: element.Type.Inout.Kind == SyntaxKind.Out ? "out " : string.Empty,
                    IdentifierName: identifierName,
                    HasFuncDef: hasFuncDef
                );
            })
            .Prepend((
                TypeKind: SyntaxKind.Identifier,
                TypeName: className,
                Out: string.Empty,
                IdentifierName: "@this",
                HasFuncDef: false)).ToImmutableArray();

        if (parametersWithThis.Any(p => p.HasFuncDef))
        {
            // TODO FuncDef fix
            return;
        }

        var parametersWithThisText = string.Join(", ", parametersWithThis.Select(p => $"{p.TypeName} {p.IdentifierName}"));

        var declarationReturnTypeName = node.ReturnType.Identifier.Kind == SyntaxKind.String
            ? "char"
            : node.ReturnType.ToStructuredString();

        var declarationParametersWithThis = node.ParameterList.Parameters
                .Select(p =>
                {
                    var element = p.Element;

                    var typeName = element.Type.Identifier.Kind == SyntaxKind.String
                        ? "const char"
                        :element.Type.ToStructuredString();

                    var identifierName = element.Identifier.Text;

                    return $"{typeName} {identifierName}";
                })
            .Prepend($"{className} {GeneratorFacts.ThisVarName}");

        var declarationParametersWithThisText = string.Join(", ", declarationParametersWithThis);

        var declaration = $"{declarationReturnTypeName} ccb::_{className}::{methodName}({declarationParametersWithThisText})";

        writer.WriteLine($"public static unsafe {node.ReturnType.Identifier.Text} {methodName}({parametersWithThisText})");
        writer.WriteLine("{");

        using (writer.Indent())
        {
            GeneratorFacts.GenerateInvokeCode(writer,
                [.. parametersWithThis.Select(p => (p.IdentifierName, p.Out, p.TypeKind))],
                declaration,
                node.ReturnType.Kind,
                node.ReturnType.Identifier.Text,
                true);
        }

        writer.WriteLine("}");
    }

    public override void VisitFieldDeclaration(FieldDeclarationSyntax node)
    {
        var classNode = (ClassDeclarationSyntax)node.Parent!;
        var className = classNode.Identifier.Text;
        var propertyName = node.Identifier.Text;
        var propertyType = node.Type.Identifier.Text;

        GenerateGet();

        if (!node.Modifiers.Any(SyntaxKind.Const))
        {
            GenerateSet();
        }

        return;

        void GenerateGet()
        {
            writer.WriteLine($"public static unsafe {propertyType} Get{propertyName}({className} @this)");
            writer.WriteLine("{");

            using (writer.Indent())
            {
                GeneratorFacts.GenerateInvokeCode(writer,
                    [("@this", string.Empty, SyntaxKind.Identifier)],
                    $"ccb::_{className}::Get{propertyName}({className})",
                    node.Type.Kind,
                    node.Type.Identifier.Text,
                    true);
            }

            writer.WriteLine("}");
        }

        void GenerateSet()
        {
            writer.WriteLine($"public static unsafe void Set{propertyName}({className} @this, {node.Type.Identifier.Text} value)");
            writer.WriteLine("{");

            using (writer.Indent())
            {
                GeneratorFacts.GenerateInvokeCode(writer,
                    [("@this", string.Empty, SyntaxKind.Identifier), ("value", string.Empty, node.Type.Identifier.Kind)],
                    $"ccb::_{className}::Set{propertyName}({className}, {node.Type.Identifier.Text})");
            }

            writer.WriteLine("}");
        }
    }
}