// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

#nullable enable
public struct Audio(ObjectOpaque opaque) : IScriptObject, IEquatable<Audio>
{
    public static Audio Null { get; } = default;

    public ObjectOpaque Opaque { get; } = opaque;

    public bool Equals(Audio other) => this.Opaque == other.Opaque;

    public override bool Equals(object? obj) => obj is Audio other && this.Equals(other);

    public override int GetHashCode() => this.Opaque.GetHashCode();

    public static bool operator ==(Audio left, Audio right) => left.Equals(right);

    public static bool operator !=(Audio left, Audio right) => !left.Equals(right);

    public static bool operator ==(Audio left, Audio? right) => right.HasValue ? left.Equals(right.Value) : left.Opaque == null;

    public static bool operator !=(Audio left, Audio? right) => !(left == right);

    public static bool operator ==(Audio? left, Audio right) => right == left;

    public static bool operator !=(Audio? left, Audio right) => !(right == left);

    public static IScriptObject Create(ObjectOpaque opaque)
    {
        return new Audio(opaque);
    }

    public Sound Play3DSound(in string filenameorurl, Player player, float range, float volume, bool norange)
    {
        return ScriptFunctions.AudioFunctions.Play3DSound(this, in filenameorurl, player, range, volume, norange);
    }

    public Sound Play3DSound(in string filenameorurl, Entity entity, float range, float volume, bool norange)
    {
        return ScriptFunctions.AudioFunctions.Play3DSound(this, in filenameorurl, entity, range, volume, norange);
    }

    public Sound Play3DSound(in string filenameorurl, float x, float y, float z, float range, float volume, bool norange)
    {
        return ScriptFunctions.AudioFunctions.Play3DSound(this, in filenameorurl, x, y, z, range, volume, norange);
    }

    public Sound PlaySound(in string filenameorurl)
    {
        return ScriptFunctions.AudioFunctions.PlaySound(this, in filenameorurl);
    }

    public Sound PlaySoundForPlayer(Player player, in string filenameorurl)
    {
        return ScriptFunctions.AudioFunctions.PlaySoundForPlayer(this, player, in filenameorurl);
    }

    public Sound Play3DSoundForPlayer(Player player, in string filenameorurl, Entity entity, float range, float volume, bool norange)
    {
        return ScriptFunctions.AudioFunctions.Play3DSoundForPlayer(this, player, in filenameorurl, entity, range, volume, norange);
    }

    public Sound Play3DSoundForPlayer(Player player, in string filenameorurl, float x, float y, float z, float range, float volume, bool norange)
    {
        return ScriptFunctions.AudioFunctions.Play3DSoundForPlayer(this, player, in filenameorurl, x, y, z, range, volume, norange);
    }

    public Sound Play3DSoundForPlayer(Player player_to, in string filenameorurl, Player player, float range, float volume, bool norange)
    {
        return ScriptFunctions.AudioFunctions.Play3DSoundForPlayer(this, player_to, in filenameorurl, player, range, volume, norange);
    }
}
