// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

#nullable enable
public struct Chat(ObjectOpaque opaque) : IScriptObject, IEquatable<Chat>
{
    public static Chat Null { get; } = default;

    public ObjectOpaque Opaque { get; } = opaque;

    public bool Equals(Chat other) => this.Opaque == other.Opaque;

    public override bool Equals(object? obj) => obj is Chat other && this.Equals(other);

    public override int GetHashCode() => this.Opaque.GetHashCode();

    public static bool operator ==(Chat left, Chat right) => left.Equals(right);

    public static bool operator !=(Chat left, Chat right) => !left.Equals(right);

    public static bool operator ==(Chat left, Chat? right) => right.HasValue ? left.Equals(right.Value) : left.Opaque == null;

    public static bool operator !=(Chat left, Chat? right) => !(left == right);

    public static bool operator ==(Chat? left, Chat right) => right == left;

    public static bool operator !=(Chat? left, Chat right) => !(right == left);

    public static IScriptObject Create(ObjectOpaque opaque)
    {
        return new Chat(opaque);
    }

    public void Send(in string message) => ScriptFunctions.ChatFunctions.Send(this, in message);

    public void SendPlayer(Player player, in string message) => ScriptFunctions.ChatFunctions.SendPlayer(this, player, in message);
}
