// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

#nullable enable
public struct Config(ObjectOpaque opaque) : IScriptObject, IEquatable<Config>
{
    public static Config Null { get; } = default;

    public ObjectOpaque Opaque { get; } = opaque;

    public struct Iterator(IteratorOpaque opaque) : IEnumerator<Config>
    {
        private IteratorOpaque _opaque = opaque;
        private Config? _current;
        public Config Current => this._current!.Value;
        object IEnumerator.Current => this._current!.Value;

        public static Iterator Create()
        {
            return new Iterator(IteratorOpaque.Create("::ConfigIterator ccb::Config::create_iterator()"));
        }

        public bool MoveNext()
        {
            if (this._opaque.IsNull("bool ccb::Config::iterator_is_null(::ConfigIterator& in iterator)"))
            {
                this._current = null;
                return false;
            }

            this._current = this._opaque.Get<Config>("::Config ccb::Config::iterator_get(::ConfigIterator& in iterator)");
            this._opaque.Advance("void ccb::Config::iterator_advance(::ConfigIterator& in iterator)");

            return true;
        }

        public void Reset()
        {
            throw new NotSupportedException();
        }

        public void Dispose()
        {
        }
    }

    public class IteratorEnumerable : IEnumerable<Config>
    {
        public Iterator GetEnumerator() => Iterator.Create();

        IEnumerator<Config> IEnumerable<Config>.GetEnumerator() => this.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();
    }

    public static IteratorEnumerable List()
    {
        return new IteratorEnumerable();
    }

    public bool Equals(Config other) => this.Opaque == other.Opaque;

    public override bool Equals(object? obj) => obj is Config other && this.Equals(other);

    public override int GetHashCode() => this.Opaque.GetHashCode();

    public static bool operator ==(Config left, Config right) => left.Equals(right);

    public static bool operator !=(Config left, Config right) => !left.Equals(right);

    public static bool operator ==(Config left, Config? right) => right.HasValue ? left.Equals(right.Value) : left.Opaque == null;

    public static bool operator !=(Config left, Config? right) => !(left == right);

    public static bool operator ==(Config? left, Config right) => right == left;

    public static bool operator !=(Config? left, Config right) => !(right == left);

    public static IScriptObject Create(ObjectOpaque opaque)
    {
        return new Config(opaque);
    }

    public bool Exist(in string key, int index)
    {
        return ScriptFunctions.ConfigFunctions.Exist(this, in key, index);
    }

    public string Get(in string key, int index)
    {
        return ScriptFunctions.ConfigFunctions.Get(this, in key, index);
    }

    public void Remove()
    {
        ScriptFunctions.ConfigFunctions.Remove(this);
    }
}
