// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

#nullable enable
public struct Connection(ObjectOpaque opaque) : IScriptObject, IEquatable<Connection>
{
    public static Connection Null { get; } = default;

    public ObjectOpaque Opaque { get; } = opaque;

    public struct Iterator(IteratorOpaque opaque) : IEnumerator<Connection>
    {
        private IteratorOpaque _opaque = opaque;
        private Connection? _current;
        public Connection Current => this._current!.Value;
        object IEnumerator.Current => this._current!.Value;

        public static Iterator Create()
        {
            return new Iterator(IteratorOpaque.Create("::ConnectionIterator ccb::Connection::create_iterator()"));
        }

        public bool MoveNext()
        {
            if (this._opaque.IsNull("bool ccb::Connection::iterator_is_null(::ConnectionIterator& in iterator)"))
            {
                this._current = null;
                return false;
            }

            this._current = this._opaque.Get<Connection>("::Connection ccb::Connection::iterator_get(::ConnectionIterator& in iterator)");
            this._opaque.Advance("void ccb::Connection::iterator_advance(::ConnectionIterator& in iterator)");

            return true;
        }

        public void Reset()
        {
            throw new NotSupportedException();
        }

        public void Dispose()
        {
        }
    }

    public class IteratorEnumerable : IEnumerable<Connection>
    {
        public Iterator GetEnumerator() => Iterator.Create();

        IEnumerator<Connection> IEnumerable<Connection>.GetEnumerator() => this.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();
    }

    public static IteratorEnumerable List()
    {
        return new IteratorEnumerable();
    }

    public bool Equals(Connection other) => this.Opaque == other.Opaque;

    public override bool Equals(object? obj) => obj is Connection other && this.Equals(other);

    public override int GetHashCode() => this.Opaque.GetHashCode();

    public static bool operator ==(Connection left, Connection right) => left.Equals(right);

    public static bool operator !=(Connection left, Connection right) => !left.Equals(right);

    public static bool operator ==(Connection left, Connection? right) => right.HasValue ? left.Equals(right.Value) : left.Opaque == null;

    public static bool operator !=(Connection left, Connection? right) => !(left == right);

    public static bool operator ==(Connection? left, Connection right) => right == left;

    public static bool operator !=(Connection? left, Connection right) => !(right == left);

    public static IScriptObject Create(ObjectOpaque opaque)
    {
        return new Connection(opaque);
    }

    public int GetPort() => ScriptFunctions.ConnectionFunctions.GetPort(this);

    public string GetName() => ScriptFunctions.ConnectionFunctions.GetName(this);

    public string GetLanguage() => ScriptFunctions.ConnectionFunctions.GetLanguage(this);

    public string GetHWID(int wmid = 0) => ScriptFunctions.ConnectionFunctions.GetHWID(this, wmid);

    public string GetIP() => ScriptFunctions.ConnectionFunctions.GetIP(this);

    public string GetSteamID() => ScriptFunctions.ConnectionFunctions.GetSteamID(this);

    public int GetQueue() => ScriptFunctions.ConnectionFunctions.GetQueue(this);

    public bool Join() => ScriptFunctions.ConnectionFunctions.Join(this);

    public void Accept() => ScriptFunctions.ConnectionFunctions.Accept(this);

    public void Cancel(int code) => ScriptFunctions.ConnectionFunctions.Cancel(this, code);

    public void Cancel(in string custom = "") => ScriptFunctions.ConnectionFunctions.Cancel(this, in custom);

    public void Remove() => ScriptFunctions.ConnectionFunctions.Remove(this);
}
