// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

#nullable enable
public struct Corpse(ObjectOpaque opaque) : IScriptObject, IEquatable<Corpse>
{
    public static Corpse Null { get; } = default;

    public ObjectOpaque Opaque { get; } = opaque;

    public struct Iterator(IteratorOpaque opaque) : IEnumerator<Corpse>
    {
        private IteratorOpaque _opaque = opaque;
        private Corpse? _current;
        public Corpse Current => this._current!.Value;
        object IEnumerator.Current => this._current!.Value;

        public static Iterator Create()
        {
            return new Iterator(IteratorOpaque.Create("::CorpseIterator ccb::Corpse::create_iterator()"));
        }

        public bool MoveNext()
        {
            if (this._opaque.IsNull("bool ccb::Corpse::iterator_is_null(::CorpseIterator& in iterator)"))
            {
                this._current = null;
                return false;
            }

            this._current = this._opaque.Get<Corpse>("::Corpse ccb::Corpse::iterator_get(::CorpseIterator& in iterator)");
            this._opaque.Advance("void ccb::Corpse::iterator_advance(::CorpseIterator& in iterator)");

            return true;
        }

        public void Reset()
        {
            throw new NotSupportedException();
        }

        public void Dispose()
        {
        }
    }

    public class IteratorEnumerable : IEnumerable<Corpse>
    {
        public Iterator GetEnumerator() => Iterator.Create();

        IEnumerator<Corpse> IEnumerable<Corpse>.GetEnumerator() => this.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();
    }

    public static IteratorEnumerable List()
    {
        return new IteratorEnumerable();
    }

    public bool Equals(Corpse other) => this.Opaque == other.Opaque;

    public override bool Equals(object? obj) => obj is Corpse other && this.Equals(other);

    public override int GetHashCode() => this.Opaque.GetHashCode();

    public static bool operator ==(Corpse left, Corpse right) => left.Equals(right);

    public static bool operator !=(Corpse left, Corpse right) => !left.Equals(right);

    public static bool operator ==(Corpse left, Corpse? right) => right.HasValue ? left.Equals(right.Value) : left.Opaque == null;

    public static bool operator !=(Corpse left, Corpse? right) => !(left == right);

    public static bool operator ==(Corpse? left, Corpse right) => right == left;

    public static bool operator !=(Corpse? left, Corpse right) => !(right == left);

    public static IScriptObject Create(ObjectOpaque opaque)
    {
        return new Corpse(opaque);
    }

    public int GetIndex() => ScriptFunctions.CorpseFunctions.GetIndex(this);

    public Player GetPlayer() => ScriptFunctions.CorpseFunctions.GetPlayer(this);

    public Entity GetEntity() => ScriptFunctions.CorpseFunctions.GetEntity(this);

    public float GetTimeout() => ScriptFunctions.CorpseFunctions.GetTimeout(this);

    public void SetTimeout(float unnamed0) => ScriptFunctions.CorpseFunctions.SetTimeout(this, unnamed0);

    public bool PushItem(Items unnamed0) => ScriptFunctions.CorpseFunctions.PushItem(this, unnamed0);

    public bool ExploreItem(int slot) => ScriptFunctions.CorpseFunctions.ExploreItem(this, slot);

    public Items GetItem(int slot) => ScriptFunctions.CorpseFunctions.GetItem(this, slot);

    public int GetModel() => ScriptFunctions.CorpseFunctions.GetModel(this);

    public int GetItemsCount() => ScriptFunctions.CorpseFunctions.GetItemsCount(this);

    public bool IsExplored() => ScriptFunctions.CorpseFunctions.IsExplored(this);

    public void SetExplore(bool explore) => ScriptFunctions.CorpseFunctions.SetExplore(this, explore);

    public bool Explore() => ScriptFunctions.CorpseFunctions.Explore(this);

    public void SetData(in string data) => ScriptFunctions.CorpseFunctions.SetData(this, in data);

    public string GetData() => ScriptFunctions.CorpseFunctions.GetData(this);

    public void Remove() => ScriptFunctions.CorpseFunctions.Remove(this);
}
