// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

#nullable enable
public struct Corpse(ObjectHandle handle) : IScriptObject, IEquatable<Corpse>
{
    public ObjectHandle Handle { get; } = handle;

    public struct Iterator(IteratorOpaque opaque) : IEnumerator<Corpse>
    {
        private IteratorOpaque _opaque = opaque;
        private Corpse? _current;
        public Corpse Current => this._current!.Value;
        object IEnumerator.Current => this._current!.Value;

        public static Iterator Create()
        {
            return new Iterator(IteratorOpaque.Create("::CorpseIterator ccb::Corpse::create_iterator()"));
        }

        public bool MoveNext()
        {
            if (this._opaque.IsNull("bool ccb::Corpse::iterator_is_null(::CorpseIterator& in iterator)"))
            {
                this._current = null;
                return false;
            }

            this._current = this._opaque.Get<Corpse>("::Corpse ccb::Corpse::iterator_get(::CorpseIterator& in iterator)");
            this._opaque.Advance("void ccb::Corpse::iterator_advance(::CorpseIterator& in iterator)");

            return true;
        }

        public void Reset()
        {
            throw new NotSupportedException();
        }

        public void Dispose()
        {
        }
    }

    public class IteratorEnumerable : IEnumerable<Corpse>
    {
        public Iterator GetEnumerator() => Iterator.Create();

        IEnumerator<Corpse> IEnumerable<Corpse>.GetEnumerator() => this.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();
    }

    public static IteratorEnumerable List()
    {
        return new IteratorEnumerable();
    }

    public bool Equals(Corpse other) => this.Handle == other.Handle;

    public override bool Equals(object? obj) => obj is Corpse other && this.Equals(other);

    public override int GetHashCode() => this.Handle.GetHashCode();

    public static bool operator ==(Corpse left, Corpse right) => left.Equals(right);

    public static bool operator !=(Corpse left, Corpse right) => !left.Equals(right);

    public static bool operator ==(Corpse left, Corpse? right) => right.HasValue ? left.Equals(right.Value) : left.Handle == null;

    public static bool operator !=(Corpse left, Corpse? right) => !(left == right);

    public static bool operator ==(Corpse? left, Corpse right) => right == left;

    public static bool operator !=(Corpse? left, Corpse right) => !(right == left);

    public static IScriptObject Create(ObjectHandle handle)
    {
        return new Corpse(handle);
    }

    public int GetIndex()
    {
        return ScriptFunctions.CorpseFunctions.GetIndex(this);
    }

    public Player GetPlayer()
    {
        return ScriptFunctions.CorpseFunctions.GetPlayer(this);
    }

    public Entity GetEntity()
    {
        return ScriptFunctions.CorpseFunctions.GetEntity(this);
    }

    public float GetTimeout()
    {
        return ScriptFunctions.CorpseFunctions.GetTimeout(this);
    }

    public void SetTimeout(float unnamed0)
    {
        ScriptFunctions.CorpseFunctions.SetTimeout(this, unnamed0);
    }

    public bool PushItem(Items unnamed0)
    {
        return ScriptFunctions.CorpseFunctions.PushItem(this, unnamed0);
    }

    public bool ExploreItem(int slot)
    {
        return ScriptFunctions.CorpseFunctions.ExploreItem(this, slot);
    }

    public Items GetItem(int slot)
    {
        return ScriptFunctions.CorpseFunctions.GetItem(this, slot);
    }

    public int GetModel()
    {
        return ScriptFunctions.CorpseFunctions.GetModel(this);
    }

    public int GetItemsCount()
    {
        return ScriptFunctions.CorpseFunctions.GetItemsCount(this);
    }

    public bool IsExplored()
    {
        return ScriptFunctions.CorpseFunctions.IsExplored(this);
    }

    public void SetExplore(bool explore)
    {
        ScriptFunctions.CorpseFunctions.SetExplore(this, explore);
    }

    public bool Explore()
    {
        return ScriptFunctions.CorpseFunctions.Explore(this);
    }

    public void SetData(in string data)
    {
        ScriptFunctions.CorpseFunctions.SetData(this, in data);
    }

    public string GetData()
    {
        return ScriptFunctions.CorpseFunctions.GetData(this);
    }

    public void Remove()
    {
        ScriptFunctions.CorpseFunctions.Remove(this);
    }
}
