// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

#nullable enable
public struct Door(ObjectOpaque opaque) : IScriptObject, IEquatable<Door>
{
    public static Door Null { get; } = default;

    public ObjectOpaque Opaque { get; } = opaque;

    public struct Iterator(IteratorOpaque opaque) : IEnumerator<Door>
    {
        private IteratorOpaque _opaque = opaque;
        private Door? _current;
        public Door Current => this._current!.Value;
        object IEnumerator.Current => this._current!.Value;

        public static Iterator Create()
        {
            return new Iterator(IteratorOpaque.Create("::DoorIterator ccb::Door::create_iterator()"));
        }

        public bool MoveNext()
        {
            if (this._opaque.IsNull("bool ccb::Door::iterator_is_null(::DoorIterator& in iterator)"))
            {
                this._current = null;
                return false;
            }

            this._current = this._opaque.Get<Door>("::Door ccb::Door::iterator_get(::DoorIterator& in iterator)");
            this._opaque.Advance("void ccb::Door::iterator_advance(::DoorIterator& in iterator)");

            return true;
        }

        public void Reset()
        {
            throw new NotSupportedException();
        }

        public void Dispose()
        {
        }
    }

    public class IteratorEnumerable : IEnumerable<Door>
    {
        public Iterator GetEnumerator() => Iterator.Create();

        IEnumerator<Door> IEnumerable<Door>.GetEnumerator() => this.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();
    }

    public static IteratorEnumerable List()
    {
        return new IteratorEnumerable();
    }

    public bool Equals(Door other) => this.Opaque == other.Opaque;

    public override bool Equals(object? obj) => obj is Door other && this.Equals(other);

    public override int GetHashCode() => this.Opaque.GetHashCode();

    public static bool operator ==(Door left, Door right) => left.Equals(right);

    public static bool operator !=(Door left, Door right) => !left.Equals(right);

    public static bool operator ==(Door left, Door? right) => right.HasValue ? left.Equals(right.Value) : left.Opaque == null;

    public static bool operator !=(Door left, Door? right) => !(left == right);

    public static bool operator ==(Door? left, Door right) => right == left;

    public static bool operator !=(Door? left, Door right) => !(right == left);

    public static IScriptObject Create(ObjectOpaque opaque)
    {
        return new Door(opaque);
    }

    public void Use()
    {
        ScriptFunctions.DoorFunctions.Use(this);
    }

    public void SetOpen(bool unnamed0)
    {
        ScriptFunctions.DoorFunctions.SetOpen(this, unnamed0);
    }

    public bool IsOpened()
    {
        return ScriptFunctions.DoorFunctions.IsOpened(this);
    }

    public bool IsBreak()
    {
        return ScriptFunctions.DoorFunctions.IsBreak(this);
    }

    public void SetLockState(int unnamed0)
    {
        ScriptFunctions.DoorFunctions.SetLockState(this, unnamed0);
    }

    public int GetLockState()
    {
        return ScriptFunctions.DoorFunctions.GetLockState(this);
    }

    public float GetOpenState()
    {
        return ScriptFunctions.DoorFunctions.GetOpenState(this);
    }

    public bool BreakDoor(float x, float y, float z)
    {
        return ScriptFunctions.DoorFunctions.BreakDoor(this, x, y, z);
    }

    public void Decompose()
    {
        ScriptFunctions.DoorFunctions.Decompose(this);
    }

    public int GetDoorAccess()
    {
        return ScriptFunctions.DoorFunctions.GetDoorAccess(this);
    }

    public int GetDoorType()
    {
        return ScriptFunctions.DoorFunctions.GetDoorType(this);
    }

    public void SetKeycard(int unnamed0)
    {
        ScriptFunctions.DoorFunctions.SetKeycard(this, unnamed0);
    }

    public int GetKeycard()
    {
        return ScriptFunctions.DoorFunctions.GetKeycard(this);
    }

    public Entity GetEntity()
    {
        return ScriptFunctions.DoorFunctions.GetEntity(this);
    }

    public Entity GetButton(int index)
    {
        return ScriptFunctions.DoorFunctions.GetButton(this, index);
    }

    public int GetIndex()
    {
        return ScriptFunctions.DoorFunctions.GetIndex(this);
    }
}
