// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

#nullable enable
public struct Event(ObjectOpaque opaque) : IScriptObject, IEquatable<Event>
{
    public static Event Null { get; } = default;

    public ObjectOpaque Opaque { get; } = opaque;

    public struct Iterator(IteratorOpaque opaque) : IEnumerator<Event>
    {
        private IteratorOpaque _opaque = opaque;
        private Event? _current;
        public Event Current => this._current!.Value;
        object IEnumerator.Current => this._current!.Value;

        public static Iterator Create()
        {
            return new Iterator(IteratorOpaque.Create("::EventIterator ccb::Event::create_iterator()"));
        }

        public bool MoveNext()
        {
            if (this._opaque.IsNull("bool ccb::Event::iterator_is_null(::EventIterator& in iterator)"))
            {
                this._current = null;
                return false;
            }

            this._current = this._opaque.Get<Event>("::Event ccb::Event::iterator_get(::EventIterator& in iterator)");
            this._opaque.Advance("void ccb::Event::iterator_advance(::EventIterator& in iterator)");

            return true;
        }

        public void Reset()
        {
            throw new NotSupportedException();
        }

        public void Dispose()
        {
        }
    }

    public class IteratorEnumerable : IEnumerable<Event>
    {
        public Iterator GetEnumerator() => Iterator.Create();

        IEnumerator<Event> IEnumerable<Event>.GetEnumerator() => this.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();
    }

    public static IteratorEnumerable List()
    {
        return new IteratorEnumerable();
    }

    public bool Equals(Event other) => this.Opaque == other.Opaque;

    public override bool Equals(object? obj) => obj is Event other && this.Equals(other);

    public override int GetHashCode() => this.Opaque.GetHashCode();

    public static bool operator ==(Event left, Event right) => left.Equals(right);

    public static bool operator !=(Event left, Event right) => !left.Equals(right);

    public static bool operator ==(Event left, Event? right) => right.HasValue ? left.Equals(right.Value) : left.Opaque == null;

    public static bool operator !=(Event left, Event? right) => !(left == right);

    public static bool operator ==(Event? left, Event right) => right == left;

    public static bool operator !=(Event? left, Event right) => !(right == left);

    public static IScriptObject Create(ObjectOpaque opaque)
    {
        return new Event(opaque);
    }

    public Room GetRoom() => ScriptFunctions.EventFunctions.GetRoom(this);

    public int GetIndex() => ScriptFunctions.EventFunctions.GetIndex(this);

    public int GetIdentifier() => ScriptFunctions.EventFunctions.GetIdentifier(this);

    public float GetState() => ScriptFunctions.EventFunctions.GetState(this);

    public float GetState2() => ScriptFunctions.EventFunctions.GetState2(this);

    public float GetState3() => ScriptFunctions.EventFunctions.GetState3(this);

    public float GetState4() => ScriptFunctions.EventFunctions.GetState4(this);

    public float SetState(float state) => ScriptFunctions.EventFunctions.SetState(this, state);

    public float SetState2(float state) => ScriptFunctions.EventFunctions.SetState2(this, state);

    public float SetState3(float state) => ScriptFunctions.EventFunctions.SetState3(this, state);

    public float SetState4(float state) => ScriptFunctions.EventFunctions.SetState4(this, state);

    public void Remove() => ScriptFunctions.EventFunctions.Remove(this);
}
