// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

#nullable enable
public struct GUIElement(ObjectOpaque opaque) : IScriptObject, IEquatable<GUIElement>
{
    public static GUIElement Null { get; } = default;

    public ObjectOpaque Opaque { get; } = opaque;

    public struct Iterator(IteratorOpaque opaque) : IEnumerator<GUIElement>
    {
        private IteratorOpaque _opaque = opaque;
        private GUIElement? _current;
        public GUIElement Current => this._current!.Value;
        object IEnumerator.Current => this._current!.Value;

        public static Iterator Create()
        {
            return new Iterator(IteratorOpaque.Create("::GUIElementIterator ccb::GUIElement::create_iterator()"));
        }

        public bool MoveNext()
        {
            if (this._opaque.IsNull("bool ccb::GUIElement::iterator_is_null(::GUIElementIterator& in iterator)"))
            {
                this._current = null;
                return false;
            }

            this._current = this._opaque.Get<GUIElement>("::GUIElement ccb::GUIElement::iterator_get(::GUIElementIterator& in iterator)");
            this._opaque.Advance("void ccb::GUIElement::iterator_advance(::GUIElementIterator& in iterator)");

            return true;
        }

        public void Reset()
        {
            throw new NotSupportedException();
        }

        public void Dispose()
        {
        }
    }

    public class IteratorEnumerable : IEnumerable<GUIElement>
    {
        public Iterator GetEnumerator() => Iterator.Create();

        IEnumerator<GUIElement> IEnumerable<GUIElement>.GetEnumerator() => this.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();
    }

    public static IteratorEnumerable List()
    {
        return new IteratorEnumerable();
    }

    public bool Equals(GUIElement other) => this.Opaque == other.Opaque;

    public override bool Equals(object? obj) => obj is GUIElement other && this.Equals(other);

    public override int GetHashCode() => this.Opaque.GetHashCode();

    public static bool operator ==(GUIElement left, GUIElement right) => left.Equals(right);

    public static bool operator !=(GUIElement left, GUIElement right) => !left.Equals(right);

    public static bool operator ==(GUIElement left, GUIElement? right) => right.HasValue ? left.Equals(right.Value) : left.Opaque == null;

    public static bool operator !=(GUIElement left, GUIElement? right) => !(left == right);

    public static bool operator ==(GUIElement? left, GUIElement right) => right == left;

    public static bool operator !=(GUIElement? left, GUIElement right) => !(right == left);

    public static IScriptObject Create(ObjectOpaque opaque)
    {
        return new GUIElement(opaque);
    }

    public void GetPosition(out float x, out float y) => ScriptFunctions.GUIElementFunctions.GetPosition(this, out x, out y);

    public void SetPosition(float x, float y) => ScriptFunctions.GUIElementFunctions.SetPosition(this, x, y);

    public void SetScale(float width, float height) => ScriptFunctions.GUIElementFunctions.SetScale(this, width, height);

    public void GetScale(out float width, out float height) => ScriptFunctions.GUIElementFunctions.GetScale(this, out width, out height);

    public void SetRotation(int degrees) => ScriptFunctions.GUIElementFunctions.SetRotation(this, degrees);

    public void GetRotation(out int degrees) => ScriptFunctions.GUIElementFunctions.GetRotation(this, out degrees);

    public void SetData(in string data) => ScriptFunctions.GUIElementFunctions.SetData(this, in data);

    public void SetText(in string text) => ScriptFunctions.GUIElementFunctions.SetText(this, in text);

    public void SetFont(int fontid) => ScriptFunctions.GUIElementFunctions.SetFont(this, fontid);

    public void SetSelectable(bool selectable) => ScriptFunctions.GUIElementFunctions.SetSelectable(this, selectable);

    public void SetShadow(bool shadowed) => ScriptFunctions.GUIElementFunctions.SetShadow(this, shadowed);

    public void SetAspect(bool keep) => ScriptFunctions.GUIElementFunctions.SetAspect(this, keep);

    public void SetOpacity(float target, float lerp) => ScriptFunctions.GUIElementFunctions.SetOpacity(this, target, lerp);

    public void SetColor(int r, int g, int b) => ScriptFunctions.GUIElementFunctions.SetColor(this, r, g, b);

    public void SetTechnique(in string technique) => ScriptFunctions.GUIElementFunctions.SetTechnique(this, in technique);

    public Player GetPlayer() => ScriptFunctions.GUIElementFunctions.GetPlayer(this);

    public void SetAttach(Player player) => ScriptFunctions.GUIElementFunctions.SetAttach(this, player);

    public void SetAttach(bool enable, float x = 0.0f, float y = 0.0f, float z = 0.0f) => ScriptFunctions.GUIElementFunctions.SetAttach(this, enable, x, y, z);

    public Player GetAttach() => ScriptFunctions.GUIElementFunctions.GetAttach(this);

    public bool GetAttach(out float x, out float y, out float z) => ScriptFunctions.GUIElementFunctions.GetAttach(this, out x, out y, out z);

    public int GetFont() => ScriptFunctions.GUIElementFunctions.GetFont(this);

    public string GetText() => ScriptFunctions.GUIElementFunctions.GetText(this);

    public string GetData() => ScriptFunctions.GUIElementFunctions.GetData(this);

    public bool IsSelectable() => ScriptFunctions.GUIElementFunctions.IsSelectable(this);

    public bool IsHidden() => ScriptFunctions.GUIElementFunctions.IsHidden(this);

    public void SetCallback(in string funcname) => ScriptFunctions.GUIElementFunctions.SetCallback(this, in funcname);

    public void SetCallback(ref IntPtr gc) => ScriptFunctions.GUIElementFunctions.SetCallback(this, gc);

    public void Hide() => ScriptFunctions.GUIElementFunctions.Hide(this);

    public void Show() => ScriptFunctions.GUIElementFunctions.Show(this);

    public void Remove() => ScriptFunctions.GUIElementFunctions.Remove(this);
}
