// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

#nullable enable
public struct Items(ObjectOpaque opaque) : IScriptObject, IEquatable<Items>
{
    public static Items Null { get; } = default;

    public ObjectOpaque Opaque { get; } = opaque;

    public struct Iterator(IteratorOpaque opaque) : IEnumerator<Items>
    {
        private IteratorOpaque _opaque = opaque;
        private Items? _current;
        public Items Current => this._current!.Value;
        object IEnumerator.Current => this._current!.Value;

        public static Iterator Create()
        {
            return new Iterator(IteratorOpaque.Create("::ItemsIterator ccb::Items::create_iterator()"));
        }

        public bool MoveNext()
        {
            if (this._opaque.IsNull("bool ccb::Items::iterator_is_null(::ItemsIterator& in iterator)"))
            {
                this._current = null;
                return false;
            }

            this._current = this._opaque.Get<Items>("::Items ccb::Items::iterator_get(::ItemsIterator& in iterator)");
            this._opaque.Advance("void ccb::Items::iterator_advance(::ItemsIterator& in iterator)");

            return true;
        }

        public void Reset()
        {
            throw new NotSupportedException();
        }

        public void Dispose()
        {
        }
    }

    public class IteratorEnumerable : IEnumerable<Items>
    {
        public Iterator GetEnumerator() => Iterator.Create();

        IEnumerator<Items> IEnumerable<Items>.GetEnumerator() => this.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();
    }

    public static IteratorEnumerable List()
    {
        return new IteratorEnumerable();
    }

    public bool Equals(Items other) => this.Opaque == other.Opaque;

    public override bool Equals(object? obj) => obj is Items other && this.Equals(other);

    public override int GetHashCode() => this.Opaque.GetHashCode();

    public static bool operator ==(Items left, Items right) => left.Equals(right);

    public static bool operator !=(Items left, Items right) => !left.Equals(right);

    public static bool operator ==(Items left, Items? right) => right.HasValue ? left.Equals(right.Value) : left.Opaque == null;

    public static bool operator !=(Items left, Items? right) => !(left == right);

    public static bool operator ==(Items? left, Items right) => right == left;

    public static bool operator !=(Items? left, Items right) => !(right == left);

    public static IScriptObject Create(ObjectOpaque opaque)
    {
        return new Items(opaque);
    }

    public bool IsPicked()
    {
        return ScriptFunctions.ItemsFunctions.IsPicked(this);
    }

    public Player GetPicker()
    {
        return ScriptFunctions.ItemsFunctions.GetPicker(this);
    }

    public bool SetPicker(Player player, float throwforce)
    {
        return ScriptFunctions.ItemsFunctions.SetPicker(this, player, throwforce);
    }

    public Entity GetEntity()
    {
        return ScriptFunctions.ItemsFunctions.GetEntity(this);
    }

    public int GetIndex()
    {
        return ScriptFunctions.ItemsFunctions.GetIndex(this);
    }

    public string GetName()
    {
        return ScriptFunctions.ItemsFunctions.GetName(this);
    }

    public string GetTemplateName()
    {
        return ScriptFunctions.ItemsFunctions.GetTemplateName(this);
    }

    public int GetTemplateIndex()
    {
        return ScriptFunctions.ItemsFunctions.GetTemplateIndex(this);
    }

    public bool IsWeapon()
    {
        return ScriptFunctions.ItemsFunctions.IsWeapon(this);
    }

    public void SetState(float state)
    {
        ScriptFunctions.ItemsFunctions.SetState(this, state);
    }

    public void SetState2(float state)
    {
        ScriptFunctions.ItemsFunctions.SetState2(this, state);
    }

    public void SetState3(float state)
    {
        ScriptFunctions.ItemsFunctions.SetState3(this, state);
    }

    public float GetState()
    {
        return ScriptFunctions.ItemsFunctions.GetState(this);
    }

    public float GetState2()
    {
        return ScriptFunctions.ItemsFunctions.GetState2(this);
    }

    public float GetState3()
    {
        return ScriptFunctions.ItemsFunctions.GetState3(this);
    }

    public Items Fine(int unnamed0)
    {
        return ScriptFunctions.ItemsFunctions.Fine(this, unnamed0);
    }

    public int GetSlots()
    {
        return ScriptFunctions.ItemsFunctions.GetSlots(this);
    }

    public Items GetParentItem()
    {
        return ScriptFunctions.ItemsFunctions.GetParentItem(this);
    }

    public Items GetSlotItem(int unnamed0)
    {
        return ScriptFunctions.ItemsFunctions.GetSlotItem(this, unnamed0);
    }

    public bool PushItem(Items unnamed0)
    {
        return ScriptFunctions.ItemsFunctions.PushItem(this, unnamed0);
    }

    public bool RemoveSlotItem(int unnamed0)
    {
        return ScriptFunctions.ItemsFunctions.RemoveSlotItem(this, unnamed0);
    }

    public void Remove()
    {
        ScriptFunctions.ItemsFunctions.Remove(this);
    }
}
