// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

#nullable enable
public struct Light(ObjectOpaque opaque) : IScriptObject, IEquatable<Light>
{
    public static Light Null { get; } = default;

    public ObjectOpaque Opaque { get; } = opaque;

    public struct Iterator(IteratorOpaque opaque) : IEnumerator<Light>
    {
        private IteratorOpaque _opaque = opaque;
        private Light? _current;
        public Light Current => this._current!.Value;
        object IEnumerator.Current => this._current!.Value;

        public static Iterator Create()
        {
            return new Iterator(IteratorOpaque.Create("::LightIterator ccb::Light::create_iterator()"));
        }

        public bool MoveNext()
        {
            if (this._opaque.IsNull("bool ccb::Light::iterator_is_null(::LightIterator& in iterator)"))
            {
                this._current = null;
                return false;
            }

            this._current = this._opaque.Get<Light>("::Light ccb::Light::iterator_get(::LightIterator& in iterator)");
            this._opaque.Advance("void ccb::Light::iterator_advance(::LightIterator& in iterator)");

            return true;
        }

        public void Reset()
        {
            throw new NotSupportedException();
        }

        public void Dispose()
        {
        }
    }

    public class IteratorEnumerable : IEnumerable<Light>
    {
        public Iterator GetEnumerator() => Iterator.Create();

        IEnumerator<Light> IEnumerable<Light>.GetEnumerator() => this.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();
    }

    public static IteratorEnumerable List()
    {
        return new IteratorEnumerable();
    }

    public bool Equals(Light other) => this.Opaque == other.Opaque;

    public override bool Equals(object? obj) => obj is Light other && this.Equals(other);

    public override int GetHashCode() => this.Opaque.GetHashCode();

    public static bool operator ==(Light left, Light right) => left.Equals(right);

    public static bool operator !=(Light left, Light right) => !left.Equals(right);

    public static bool operator ==(Light left, Light? right) => right.HasValue ? left.Equals(right.Value) : left.Opaque == null;

    public static bool operator !=(Light left, Light? right) => !(left == right);

    public static bool operator ==(Light? left, Light right) => right == left;

    public static bool operator !=(Light? left, Light right) => !(right == left);

    public static IScriptObject Create(ObjectOpaque opaque)
    {
        return new Light(opaque);
    }

    public int GetIndex() => ScriptFunctions.LightFunctions.GetIndex(this);

    public void SetFOV(float fov) => ScriptFunctions.LightFunctions.SetFOV(this, fov);

    public void SetRange(float range) => ScriptFunctions.LightFunctions.SetRange(this, range);

    public void SetScattering(float scattering) => ScriptFunctions.LightFunctions.SetScattering(this, scattering);

    public void SetColor(int r, int g, int b) => ScriptFunctions.LightFunctions.SetColor(this, r, g, b);

    public void SetCastShadows(bool shadows) => ScriptFunctions.LightFunctions.SetCastShadows(this, shadows);

    public void SetIntensity(float intensity) => ScriptFunctions.LightFunctions.SetIntensity(this, intensity);

    public void SetLength(float length) => ScriptFunctions.LightFunctions.SetLength(this, length);

    public float GetFOV() => ScriptFunctions.LightFunctions.GetFOV(this);

    public float GetRange() => ScriptFunctions.LightFunctions.GetRange(this);

    public float GetScattering() => ScriptFunctions.LightFunctions.GetScattering(this);

    public void GetColor(out int r, out int g, out int b) => ScriptFunctions.LightFunctions.GetColor(this, out r, out g, out b);

    public bool GetCastShadows() => ScriptFunctions.LightFunctions.GetCastShadows(this);

    public float GetIntensity() => ScriptFunctions.LightFunctions.GetIntensity(this);

    public float GetLength() => ScriptFunctions.LightFunctions.GetLength(this);

    public void SetAttach(Player player) => ScriptFunctions.LightFunctions.SetAttach(this, player);

    public Player GetAttach() => ScriptFunctions.LightFunctions.GetAttach(this);

    public void SetRoom(Room unnamed0) => ScriptFunctions.LightFunctions.SetRoom(this, unnamed0);

    public Room GetRoom() => ScriptFunctions.LightFunctions.GetRoom(this);

    public Entity GetEntity() => ScriptFunctions.LightFunctions.GetEntity(this);

    public Entity GetLight() => ScriptFunctions.LightFunctions.GetLight(this);

    public void SetMovement(float speed, float maxdistance) => ScriptFunctions.LightFunctions.SetMovement(this, speed, maxdistance);

    public void Remove() => ScriptFunctions.LightFunctions.Remove(this);
}
