// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

#nullable enable
public struct ModelPreset(ObjectOpaque opaque) : IScriptObject, IEquatable<ModelPreset>
{
    public static ModelPreset Null { get; } = default;

    public ObjectOpaque Opaque { get; } = opaque;

    public struct Iterator(IteratorOpaque opaque) : IEnumerator<ModelPreset>
    {
        private IteratorOpaque _opaque = opaque;
        private ModelPreset? _current;
        public ModelPreset Current => this._current!.Value;
        object IEnumerator.Current => this._current!.Value;

        public static Iterator Create()
        {
            return new Iterator(IteratorOpaque.Create("::ModelPresetIterator ccb::ModelPreset::create_iterator()"));
        }

        public bool MoveNext()
        {
            if (this._opaque.IsNull("bool ccb::ModelPreset::iterator_is_null(::ModelPresetIterator& in iterator)"))
            {
                this._current = null;
                return false;
            }

            this._current = this._opaque.Get<ModelPreset>("::ModelPreset ccb::ModelPreset::iterator_get(::ModelPresetIterator& in iterator)");
            this._opaque.Advance("void ccb::ModelPreset::iterator_advance(::ModelPresetIterator& in iterator)");

            return true;
        }

        public void Reset()
        {
            throw new NotSupportedException();
        }

        public void Dispose()
        {
        }
    }

    public class IteratorEnumerable : IEnumerable<ModelPreset>
    {
        public Iterator GetEnumerator() => Iterator.Create();

        IEnumerator<ModelPreset> IEnumerable<ModelPreset>.GetEnumerator() => this.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();
    }

    public static IteratorEnumerable List()
    {
        return new IteratorEnumerable();
    }

    public bool Equals(ModelPreset other) => this.Opaque == other.Opaque;

    public override bool Equals(object? obj) => obj is ModelPreset other && this.Equals(other);

    public override int GetHashCode() => this.Opaque.GetHashCode();

    public static bool operator ==(ModelPreset left, ModelPreset right) => left.Equals(right);

    public static bool operator !=(ModelPreset left, ModelPreset right) => !left.Equals(right);

    public static bool operator ==(ModelPreset left, ModelPreset? right) => right.HasValue ? left.Equals(right.Value) : left.Opaque == null;

    public static bool operator !=(ModelPreset left, ModelPreset? right) => !(left == right);

    public static bool operator ==(ModelPreset? left, ModelPreset right) => right == left;

    public static bool operator !=(ModelPreset? left, ModelPreset right) => !(right == left);

    public static IScriptObject Create(ObjectOpaque opaque)
    {
        return new ModelPreset(opaque);
    }

    public string headbone
    {
        get => ScriptFunctions.ModelPresetFunctions.Getheadbone(this);
    }

    public string spinebone
    {
        get => ScriptFunctions.ModelPresetFunctions.Getspinebone(this);
    }

    public string handbone
    {
        get => ScriptFunctions.ModelPresetFunctions.Gethandbone(this);
    }

    public string forearmbone
    {
        get => ScriptFunctions.ModelPresetFunctions.Getforearmbone(this);
    }

    public int maximumspinepitch
    {
        get => ScriptFunctions.ModelPresetFunctions.Getmaximumspinepitch(this);
    }

    public int maximumspinepitchdist
    {
        get => ScriptFunctions.ModelPresetFunctions.Getmaximumspinepitchdist(this);
    }

    public int maximumheadpitch
    {
        get => ScriptFunctions.ModelPresetFunctions.Getmaximumheadpitch(this);
    }

    public int fixedspinerotation
    {
        get => ScriptFunctions.ModelPresetFunctions.Getfixedspinerotation(this);
    }

    public bool usedefaultrolls
    {
        get => ScriptFunctions.ModelPresetFunctions.Getusedefaultrolls(this);
    }

    public float offsetyaw
    {
        get => ScriptFunctions.ModelPresetFunctions.Getoffsetyaw(this);
    }

    public float offsety
    {
        get => ScriptFunctions.ModelPresetFunctions.Getoffsety(this);
    }

    public float collisionradius
    {
        get => ScriptFunctions.ModelPresetFunctions.Getcollisionradius(this);
    }

    public float scale
    {
        get => ScriptFunctions.ModelPresetFunctions.Getscale(this);
    }

    public string stepsound
    {
        get => ScriptFunctions.ModelPresetFunctions.Getstepsound(this);
    }

    public float blobshadowsize
    {
        get => ScriptFunctions.ModelPresetFunctions.Getblobshadowsize(this);
    }

    public float forearmholdingpitch
    {
        get => ScriptFunctions.ModelPresetFunctions.Getforearmholdingpitch(this);
    }

    public float forearmholdingyaw
    {
        get => ScriptFunctions.ModelPresetFunctions.Getforearmholdingyaw(this);
    }

    public float forearmholdingroll
    {
        get => ScriptFunctions.ModelPresetFunctions.Getforearmholdingroll(this);
    }

    public float holdingitemoffsetx
    {
        get => ScriptFunctions.ModelPresetFunctions.Getholdingitemoffsetx(this);
    }

    public float holdingitemoffsety
    {
        get => ScriptFunctions.ModelPresetFunctions.Getholdingitemoffsety(this);
    }

    public float holdingitemoffsetz
    {
        get => ScriptFunctions.ModelPresetFunctions.Getholdingitemoffsetz(this);
    }

    public float holdingitemoffsetpitch
    {
        get => ScriptFunctions.ModelPresetFunctions.Getholdingitemoffsetpitch(this);
    }

    public float holdingitemoffsetyaw
    {
        get => ScriptFunctions.ModelPresetFunctions.Getholdingitemoffsetyaw(this);
    }

    public float holdingitemoffsetroll
    {
        get => ScriptFunctions.ModelPresetFunctions.Getholdingitemoffsetroll(this);
    }

    public float hitboxwidth
    {
        get => ScriptFunctions.ModelPresetFunctions.Gethitboxwidth(this);
    }

    public float hitboxheight
    {
        get => ScriptFunctions.ModelPresetFunctions.Gethitboxheight(this);
    }

    public float hitboxdepth
    {
        get => ScriptFunctions.ModelPresetFunctions.Gethitboxdepth(this);
    }

    public float speed
    {
        get => ScriptFunctions.ModelPresetFunctions.Getspeed(this);
    }

    public float stamina
    {
        get => ScriptFunctions.ModelPresetFunctions.Getstamina(this);
    }

    public string movesound
    {
        get => ScriptFunctions.ModelPresetFunctions.Getmovesound(this);
    }

    public bool disablejump
    {
        get => ScriptFunctions.ModelPresetFunctions.Getdisablejump(this);
    }

    public int collisiontype
    {
        get => ScriptFunctions.ModelPresetFunctions.Getcollisiontype(this);
    }

    public float viewoffsety
    {
        get => ScriptFunctions.ModelPresetFunctions.Getviewoffsety(this);
    }

    public bool disableroll
    {
        get => ScriptFunctions.ModelPresetFunctions.Getdisableroll(this);
    }

    public bool disablebloodloss
    {
        get => ScriptFunctions.ModelPresetFunctions.Getdisablebloodloss(this);
    }

    public bool disableinjuries
    {
        get => ScriptFunctions.ModelPresetFunctions.Getdisableinjuries(this);
    }

    public bool flippitch
    {
        get => ScriptFunctions.ModelPresetFunctions.Getflippitch(this);
    }

    public bool disableinteractitems
    {
        get => ScriptFunctions.ModelPresetFunctions.Getdisableinteractitems(this);
    }

    public int rotationmode
    {
        get => ScriptFunctions.ModelPresetFunctions.Getrotationmode(this);
    }

    public int comparedspinerotation
    {
        get => ScriptFunctions.ModelPresetFunctions.Getcomparedspinerotation(this);
    }

    public int material
    {
        get => ScriptFunctions.ModelPresetFunctions.Getmaterial(this);
    }

    public bool constantinvisibility
    {
        get => ScriptFunctions.ModelPresetFunctions.Getconstantinvisibility(this);
    }

    public float lightradius
    {
        get => ScriptFunctions.ModelPresetFunctions.Getlightradius(this);
    }

    public int lightshadows
    {
        get => ScriptFunctions.ModelPresetFunctions.Getlightshadows(this);
    }

    public int lightr
    {
        get => ScriptFunctions.ModelPresetFunctions.Getlightr(this);
    }

    public int lightg
    {
        get => ScriptFunctions.ModelPresetFunctions.Getlightg(this);
    }

    public int lightb
    {
        get => ScriptFunctions.ModelPresetFunctions.Getlightb(this);
    }

    public float lightscattering
    {
        get => ScriptFunctions.ModelPresetFunctions.Getlightscattering(this);
    }
}
