// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

#nullable enable
public struct NPC(ObjectOpaque opaque) : IScriptObject, IEquatable<NPC>
{
    public static NPC Null { get; } = default;

    public ObjectOpaque Opaque { get; } = opaque;

    public struct Iterator(IteratorOpaque opaque) : IEnumerator<NPC>
    {
        private IteratorOpaque _opaque = opaque;
        private NPC? _current;
        public NPC Current => this._current!.Value;
        object IEnumerator.Current => this._current!.Value;

        public static Iterator Create()
        {
            return new Iterator(IteratorOpaque.Create("::NPCIterator ccb::NPC::create_iterator()"));
        }

        public bool MoveNext()
        {
            if (this._opaque.IsNull("bool ccb::NPC::iterator_is_null(::NPCIterator& in iterator)"))
            {
                this._current = null;
                return false;
            }

            this._current = this._opaque.Get<NPC>("::NPC ccb::NPC::iterator_get(::NPCIterator& in iterator)");
            this._opaque.Advance("void ccb::NPC::iterator_advance(::NPCIterator& in iterator)");

            return true;
        }

        public void Reset()
        {
            throw new NotSupportedException();
        }

        public void Dispose()
        {
        }
    }

    public class IteratorEnumerable : IEnumerable<NPC>
    {
        public Iterator GetEnumerator() => Iterator.Create();

        IEnumerator<NPC> IEnumerable<NPC>.GetEnumerator() => this.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();
    }

    public static IteratorEnumerable List()
    {
        return new IteratorEnumerable();
    }

    public bool Equals(NPC other) => this.Opaque == other.Opaque;

    public override bool Equals(object? obj) => obj is NPC other && this.Equals(other);

    public override int GetHashCode() => this.Opaque.GetHashCode();

    public static bool operator ==(NPC left, NPC right) => left.Equals(right);

    public static bool operator !=(NPC left, NPC right) => !left.Equals(right);

    public static bool operator ==(NPC left, NPC? right) => right.HasValue ? left.Equals(right.Value) : left.Opaque == null;

    public static bool operator !=(NPC left, NPC? right) => !(left == right);

    public static bool operator ==(NPC? left, NPC right) => right == left;

    public static bool operator !=(NPC? left, NPC right) => !(right == left);

    public static IScriptObject Create(ObjectOpaque opaque)
    {
        return new NPC(opaque);
    }

    public Entity GetEntity()
    {
        return ScriptFunctions.NPCFunctions.GetEntity(this);
    }

    public Entity GetModel()
    {
        return ScriptFunctions.NPCFunctions.GetModel(this);
    }

    public void SetPickable(bool pickable)
    {
        ScriptFunctions.NPCFunctions.SetPickable(this, pickable);
    }

    public void SetDead(bool state)
    {
        ScriptFunctions.NPCFunctions.SetDead(this, state);
    }

    public bool IsDead()
    {
        return ScriptFunctions.NPCFunctions.IsDead(this);
    }

    public void SetHealth(int health)
    {
        ScriptFunctions.NPCFunctions.SetHealth(this, health);
    }

    public int GetHealth()
    {
        return ScriptFunctions.NPCFunctions.GetHealth(this);
    }

    public void SetIdle(float state)
    {
        ScriptFunctions.NPCFunctions.SetIdle(this, state);
    }

    public void SetState1(float state)
    {
        ScriptFunctions.NPCFunctions.SetState1(this, state);
    }

    public void SetState2(float state)
    {
        ScriptFunctions.NPCFunctions.SetState2(this, state);
    }

    public void SetState3(float state)
    {
        ScriptFunctions.NPCFunctions.SetState3(this, state);
    }

    public float GetIdle()
    {
        return ScriptFunctions.NPCFunctions.GetIdle(this);
    }

    public float GetState1()
    {
        return ScriptFunctions.NPCFunctions.GetState1(this);
    }

    public float GetState2()
    {
        return ScriptFunctions.NPCFunctions.GetState2(this);
    }

    public float GetState3()
    {
        return ScriptFunctions.NPCFunctions.GetState3(this);
    }

    public void Remove()
    {
        ScriptFunctions.NPCFunctions.Remove(this);
    }
}
