// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

#nullable enable
public struct Server(ObjectOpaque opaque) : IScriptObject, IEquatable<Server>
{
    public static Server Null { get; } = default;

    public ObjectOpaque Opaque { get; } = opaque;

    public bool Equals(Server other) => this.Opaque == other.Opaque;

    public override bool Equals(object? obj) => obj is Server other && this.Equals(other);

    public override int GetHashCode() => this.Opaque.GetHashCode();

    public static bool operator ==(Server left, Server right) => left.Equals(right);

    public static bool operator !=(Server left, Server right) => !left.Equals(right);

    public static bool operator ==(Server left, Server? right) => right.HasValue ? left.Equals(right.Value) : left.Opaque == null;

    public static bool operator !=(Server left, Server? right) => !(left == right);

    public static bool operator ==(Server? left, Server right) => right == left;

    public static bool operator !=(Server? left, Server right) => !(right == left);

    public static IScriptObject Create(ObjectOpaque opaque)
    {
        return new Server(opaque);
    }

    public string hostname
    {
        get => ScriptFunctions.ServerFunctions.Gethostname(this);
        set => ScriptFunctions.ServerFunctions.Sethostname(this, value);
    }

    public int port
    {
        get => ScriptFunctions.ServerFunctions.Getport(this);
        set => ScriptFunctions.ServerFunctions.Setport(this, value);
    }

    public int corpsealivetime
    {
        get => ScriptFunctions.ServerFunctions.Getcorpsealivetime(this);
        set => ScriptFunctions.ServerFunctions.Setcorpsealivetime(this, value);
    }

    public int timeout
    {
        get => ScriptFunctions.ServerFunctions.Gettimeout(this);
        set => ScriptFunctions.ServerFunctions.Settimeout(this, value);
    }

    public bool chat
    {
        get => ScriptFunctions.ServerFunctions.Getchat(this);
        set => ScriptFunctions.ServerFunctions.Setchat(this, value);
    }

    public bool console
    {
        get => ScriptFunctions.ServerFunctions.Getconsole(this);
        set => ScriptFunctions.ServerFunctions.Setconsole(this, value);
    }

    public int voicebitrate
    {
        get => ScriptFunctions.ServerFunctions.Getvoicebitrate(this);
        set => ScriptFunctions.ServerFunctions.Setvoicebitrate(this, value);
    }

    public int maxplayers
    {
        get => ScriptFunctions.ServerFunctions.Getmaxplayers(this);
        set => ScriptFunctions.ServerFunctions.Setmaxplayers(this, value);
    }

    public string mapseed
    {
        get => ScriptFunctions.ServerFunctions.Getmapseed(this);
        set => ScriptFunctions.ServerFunctions.Setmapseed(this, value);
    }

    public string adminpassword
    {
        get => ScriptFunctions.ServerFunctions.Getadminpassword(this);
        set => ScriptFunctions.ServerFunctions.Setadminpassword(this, value);
    }

    public int difficulty
    {
        get => ScriptFunctions.ServerFunctions.Getdifficulty(this);
        set => ScriptFunctions.ServerFunctions.Setdifficulty(this, value);
    }

    public string gamemode
    {
        get => ScriptFunctions.ServerFunctions.Getgamemode(this);
        set => ScriptFunctions.ServerFunctions.Setgamemode(this, value);
    }

    public int emptybehaviour
    {
        get => ScriptFunctions.ServerFunctions.Getemptybehaviour(this);
        set => ScriptFunctions.ServerFunctions.Setemptybehaviour(this, value);
    }

    public bool scriptsautoload
    {
        get => ScriptFunctions.ServerFunctions.Getscriptsautoload(this);
        set => ScriptFunctions.ServerFunctions.Setscriptsautoload(this, value);
    }

    public bool disablenpcs
    {
        get => ScriptFunctions.ServerFunctions.Getdisablenpcs(this);
        set => ScriptFunctions.ServerFunctions.Setdisablenpcs(this, value);
    }

    public float proximityplayers
    {
        get => ScriptFunctions.ServerFunctions.Getproximityplayers(this);
        set => ScriptFunctions.ServerFunctions.Setproximityplayers(this, value);
    }

    public float mapbounds
    {
        get => ScriptFunctions.ServerFunctions.Getmapbounds(this);
        set => ScriptFunctions.ServerFunctions.Setmapbounds(this, value);
    }

    public int respawntime
    {
        get => ScriptFunctions.ServerFunctions.Getrespawntime(this);
        set => ScriptFunctions.ServerFunctions.Setrespawntime(this, value);
    }

    public string contenturl
    {
        get => ScriptFunctions.ServerFunctions.Getcontenturl(this);
        set => ScriptFunctions.ServerFunctions.Setcontenturl(this, value);
    }

    public string password
    {
        get => ScriptFunctions.ServerFunctions.Getpassword(this);
        set => ScriptFunctions.ServerFunctions.Setpassword(this, value);
    }

    public bool improvedgates
    {
        get => ScriptFunctions.ServerFunctions.Getimprovedgates(this);
        set => ScriptFunctions.ServerFunctions.Setimprovedgates(this, value);
    }

    public int mapsize
    {
        get => ScriptFunctions.ServerFunctions.Getmapsize(this);
        set => ScriptFunctions.ServerFunctions.Setmapsize(this, value);
    }

    public bool allowjump
    {
        get => ScriptFunctions.ServerFunctions.Getallowjump(this);
        set => ScriptFunctions.ServerFunctions.Setallowjump(this, value);
    }

    public string description
    {
        get => ScriptFunctions.ServerFunctions.Getdescription(this);
        set => ScriptFunctions.ServerFunctions.Setdescription(this, value);
    }

    public bool fastslots
    {
        get => ScriptFunctions.ServerFunctions.Getfastslots(this);
        set => ScriptFunctions.ServerFunctions.Setfastslots(this, value);
    }

    public float gravity
    {
        get => ScriptFunctions.ServerFunctions.Getgravity(this);
        set => ScriptFunctions.ServerFunctions.Setgravity(this, value);
    }

    public int holiday
    {
        get => ScriptFunctions.ServerFunctions.Getholiday(this);
        set => ScriptFunctions.ServerFunctions.Setholiday(this, value);
    }

    public string addonsfile
    {
        get => ScriptFunctions.ServerFunctions.Getaddonsfile(this);
        set => ScriptFunctions.ServerFunctions.Setaddonsfile(this, value);
    }

    public bool enablehud
    {
        get => ScriptFunctions.ServerFunctions.Getenablehud(this);
        set => ScriptFunctions.ServerFunctions.Setenablehud(this, value);
    }

    public int max_items
    {
        get => ScriptFunctions.ServerFunctions.Getmax_items(this);
        set => ScriptFunctions.ServerFunctions.Setmax_items(this, value);
    }

    public int max_objects
    {
        get => ScriptFunctions.ServerFunctions.Getmax_objects(this);
        set => ScriptFunctions.ServerFunctions.Setmax_objects(this, value);
    }

    public int max_corpses
    {
        get => ScriptFunctions.ServerFunctions.Getmax_corpses(this);
        set => ScriptFunctions.ServerFunctions.Setmax_corpses(this, value);
    }

    public int max_lights
    {
        get => ScriptFunctions.ServerFunctions.Getmax_lights(this);
        set => ScriptFunctions.ServerFunctions.Setmax_lights(this, value);
    }

    public bool player_culling
    {
        get => ScriptFunctions.ServerFunctions.Getplayer_culling(this);
        set => ScriptFunctions.ServerFunctions.Setplayer_culling(this, value);
    }

    public bool steam_auth
    {
        get => ScriptFunctions.ServerFunctions.Getsteam_auth(this);
        set => ScriptFunctions.ServerFunctions.Setsteam_auth(this, value);
    }

    public bool fall_damage
    {
        get => ScriptFunctions.ServerFunctions.Getfall_damage(this);
        set => ScriptFunctions.ServerFunctions.Setfall_damage(this, value);
    }

    public void Restart() => ScriptFunctions.ServerFunctions.Restart(this);

    public void Console(in string unnamed0) => ScriptFunctions.ServerFunctions.Console(this, in unnamed0);

    public string GetVersion() => ScriptFunctions.ServerFunctions.GetVersion(this);

    public void AddVersion(in string version) => ScriptFunctions.ServerFunctions.AddVersion(this, in version);

    public void RemoveVersion(in string version) => ScriptFunctions.ServerFunctions.RemoveVersion(this, in version);

    public int GetUPS() => ScriptFunctions.ServerFunctions.GetUPS(this);

    public Config ParseConfig(in string filename) => ScriptFunctions.ServerFunctions.ParseConfig(this, in filename);
}
