// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

#nullable enable
public struct Shell(ObjectOpaque opaque) : IScriptObject, IEquatable<Shell>
{
    public static Shell Null { get; } = default;

    public ObjectOpaque Opaque { get; } = opaque;

    public struct Iterator(IteratorOpaque opaque) : IEnumerator<Shell>
    {
        private IteratorOpaque _opaque = opaque;
        private Shell? _current;
        public Shell Current => this._current!.Value;
        object IEnumerator.Current => this._current!.Value;

        public static Iterator Create()
        {
            return new Iterator(IteratorOpaque.Create("::ShellIterator ccb::Shell::create_iterator()"));
        }

        public bool MoveNext()
        {
            if (this._opaque.IsNull("bool ccb::Shell::iterator_is_null(::ShellIterator& in iterator)"))
            {
                this._current = null;
                return false;
            }

            this._current = this._opaque.Get<Shell>("::Shell ccb::Shell::iterator_get(::ShellIterator& in iterator)");
            this._opaque.Advance("void ccb::Shell::iterator_advance(::ShellIterator& in iterator)");

            return true;
        }

        public void Reset()
        {
            throw new NotSupportedException();
        }

        public void Dispose()
        {
        }
    }

    public class IteratorEnumerable : IEnumerable<Shell>
    {
        public Iterator GetEnumerator() => Iterator.Create();

        IEnumerator<Shell> IEnumerable<Shell>.GetEnumerator() => this.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();
    }

    public static IteratorEnumerable List()
    {
        return new IteratorEnumerable();
    }

    public bool Equals(Shell other) => this.Opaque == other.Opaque;

    public override bool Equals(object? obj) => obj is Shell other && this.Equals(other);

    public override int GetHashCode() => this.Opaque.GetHashCode();

    public static bool operator ==(Shell left, Shell right) => left.Equals(right);

    public static bool operator !=(Shell left, Shell right) => !left.Equals(right);

    public static bool operator ==(Shell left, Shell? right) => right.HasValue ? left.Equals(right.Value) : left.Opaque == null;

    public static bool operator !=(Shell left, Shell? right) => !(left == right);

    public static bool operator ==(Shell? left, Shell right) => right == left;

    public static bool operator !=(Shell? left, Shell right) => !(right == left);

    public static IScriptObject Create(ObjectOpaque opaque)
    {
        return new Shell(opaque);
    }

    public Entity GetEntity() => ScriptFunctions.ShellFunctions.GetEntity(this);

    public int GetIndex() => ScriptFunctions.ShellFunctions.GetIndex(this);

    public void GetVelocity(out float x, out float y, out float z) => ScriptFunctions.ShellFunctions.GetVelocity(this, out x, out y, out z);

    public string GetActionEmitter() => ScriptFunctions.ShellFunctions.GetActionEmitter(this);

    public int GetEmitter() => ScriptFunctions.ShellFunctions.GetEmitter(this);

    public string GetActionSound() => ScriptFunctions.ShellFunctions.GetActionSound(this);

    public string GetCollisionSound() => ScriptFunctions.ShellFunctions.GetCollisionSound(this);

    public string GetSound() => ScriptFunctions.ShellFunctions.GetSound(this);

    public float GetSpeed() => ScriptFunctions.ShellFunctions.GetSpeed(this);

    public float GetForce() => ScriptFunctions.ShellFunctions.GetForce(this);

    public float GetRestitution() => ScriptFunctions.ShellFunctions.GetRestitution(this);

    public float GetGravity() => ScriptFunctions.ShellFunctions.GetGravity(this);

    public float GetCollisionRadius() => ScriptFunctions.ShellFunctions.GetCollisionRadius(this);

    public float GetDamage() => ScriptFunctions.ShellFunctions.GetDamage(this);

    public float GetTimeout() => ScriptFunctions.ShellFunctions.GetTimeout(this);

    public float GetImpactTime() => ScriptFunctions.ShellFunctions.GetImpactTime(this);

    public int GetAction() => ScriptFunctions.ShellFunctions.GetAction(this);

    public float GetActionRadius() => ScriptFunctions.ShellFunctions.GetActionRadius(this);

    public bool IsSticky() => ScriptFunctions.ShellFunctions.IsSticky(this);

    public uint GetStickFlags() => ScriptFunctions.ShellFunctions.GetStickFlags(this);

    public int GetStickIndex() => ScriptFunctions.ShellFunctions.GetStickIndex(this);

    public int GetWeapon() => ScriptFunctions.ShellFunctions.GetWeapon(this);

    public Player GetShooter() => ScriptFunctions.ShellFunctions.GetShooter(this);

    public void Unstick() => ScriptFunctions.ShellFunctions.Unstick(this);

    public void SetSticky(bool sticky) => ScriptFunctions.ShellFunctions.SetSticky(this, sticky);

    public void SetVelocity(float x, float y, float z) => ScriptFunctions.ShellFunctions.SetVelocity(this, x, y, z);

    public void SetActionEmitter(in string emitters) => ScriptFunctions.ShellFunctions.SetActionEmitter(this, in emitters);

    public void SetEmitter(int id) => ScriptFunctions.ShellFunctions.SetEmitter(this, id);

    public void SetActionSound(in string sound) => ScriptFunctions.ShellFunctions.SetActionSound(this, in sound);

    public void SetCollisionSound(in string sound) => ScriptFunctions.ShellFunctions.SetCollisionSound(this, in sound);

    public void SetSound(in string sound) => ScriptFunctions.ShellFunctions.SetSound(this, in sound);

    public void SetSpeed(float speed) => ScriptFunctions.ShellFunctions.SetSpeed(this, speed);

    public void SetForce(float force) => ScriptFunctions.ShellFunctions.SetForce(this, force);

    public void SetRestitution(float restitution) => ScriptFunctions.ShellFunctions.SetRestitution(this, restitution);

    public void SetGravity(float gravity) => ScriptFunctions.ShellFunctions.SetGravity(this, gravity);

    public void SetCollisionRadius(float radius) => ScriptFunctions.ShellFunctions.SetCollisionRadius(this, radius);

    public void SetTimeout(float time) => ScriptFunctions.ShellFunctions.SetTimeout(this, time);

    public void SetImpactTime(float time) => ScriptFunctions.ShellFunctions.SetImpactTime(this, time);

    public void SetDamage(float damage) => ScriptFunctions.ShellFunctions.SetDamage(this, damage);

    public void SetAction(int action) => ScriptFunctions.ShellFunctions.SetAction(this, action);

    public void SetActionRadius(float radius) => ScriptFunctions.ShellFunctions.SetActionRadius(this, radius);

    public void SetShooter(Player player) => ScriptFunctions.ShellFunctions.SetShooter(this, player);

    public void Remove(bool action) => ScriptFunctions.ShellFunctions.Remove(this, action);
}
