// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

#nullable enable
public struct Sound(ObjectOpaque opaque) : IScriptObject, IEquatable<Sound>
{
    public static Sound Null { get; } = default;

    public ObjectOpaque Opaque { get; } = opaque;

    public struct Iterator(IteratorOpaque opaque) : IEnumerator<Sound>
    {
        private IteratorOpaque _opaque = opaque;
        private Sound? _current;
        public Sound Current => this._current!.Value;
        object IEnumerator.Current => this._current!.Value;

        public static Iterator Create()
        {
            return new Iterator(IteratorOpaque.Create("::SoundIterator ccb::Sound::create_iterator()"));
        }

        public bool MoveNext()
        {
            if (this._opaque.IsNull("bool ccb::Sound::iterator_is_null(::SoundIterator& in iterator)"))
            {
                this._current = null;
                return false;
            }

            this._current = this._opaque.Get<Sound>("::Sound ccb::Sound::iterator_get(::SoundIterator& in iterator)");
            this._opaque.Advance("void ccb::Sound::iterator_advance(::SoundIterator& in iterator)");

            return true;
        }

        public void Reset()
        {
            throw new NotSupportedException();
        }

        public void Dispose()
        {
        }
    }

    public class IteratorEnumerable : IEnumerable<Sound>
    {
        public Iterator GetEnumerator() => Iterator.Create();

        IEnumerator<Sound> IEnumerable<Sound>.GetEnumerator() => this.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();
    }

    public static IteratorEnumerable List()
    {
        return new IteratorEnumerable();
    }

    public bool Equals(Sound other) => this.Opaque == other.Opaque;

    public override bool Equals(object? obj) => obj is Sound other && this.Equals(other);

    public override int GetHashCode() => this.Opaque.GetHashCode();

    public static bool operator ==(Sound left, Sound right) => left.Equals(right);

    public static bool operator !=(Sound left, Sound right) => !left.Equals(right);

    public static bool operator ==(Sound left, Sound? right) => right.HasValue ? left.Equals(right.Value) : left.Opaque == null;

    public static bool operator !=(Sound left, Sound? right) => !(left == right);

    public static bool operator ==(Sound? left, Sound right) => right == left;

    public static bool operator !=(Sound? left, Sound right) => !(right == left);

    public static IScriptObject Create(ObjectOpaque opaque)
    {
        return new Sound(opaque);
    }

    public void SetVolume(float vol) => ScriptFunctions.SoundFunctions.SetVolume(this, vol);

    public void Seek(float time) => ScriptFunctions.SoundFunctions.Seek(this, time);

    public void Stop() => ScriptFunctions.SoundFunctions.Stop(this);
}
