// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

public struct Chat(ObjectHandle handle) : IScriptObject
{
    public ObjectHandle Handle { get; } = handle;

    public static IScriptObject Create(ObjectHandle handle)
    {
        return new Chat(handle);
    }

    public void Send(in string message)
    {
        ScriptFunctions.ChatFunctions.Send(this, in message);
    }

    public void SendPlayer(Player player, in string message)
    {
        ScriptFunctions.ChatFunctions.SendPlayer(this, player, in message);
    }
}
