// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

public struct Object(ObjectHandle handle) : IScriptObject
{
    public ObjectHandle Handle { get; } = handle;

    public struct Iterator(IteratorOpaque opaque) : IEnumerator<Object>
    {
        private IteratorOpaque _opaque = opaque;
        private Object? _current;
        public Object Current => this._current!.Value;
        object IEnumerator.Current => this._current!.Value;

        public static Iterator Create()
        {
            return new Iterator(IteratorOpaque.Create("::ObjectIterator ccb::Object::create_iterator()"));
        }

        public bool MoveNext()
        {
            if (this._opaque.IsNull("bool ccb::Object::iterator_is_null(::ObjectIterator& in iterator)"))
            {
                this._current = null;
                return false;
            }

            this._current = this._opaque.Get<Object>("::Object ccb::Object::iterator_get(::ObjectIterator& in iterator)");
            this._opaque.Advance("void ccb::Object::iterator_advance(::ObjectIterator& in iterator)");

            return true;
        }

        public void Reset()
        {
            throw new NotSupportedException();
        }

        public void Dispose()
        {
        }
    }

    public class IteratorEnumerable : IEnumerable<Object>
    {
        public Iterator GetEnumerator() => Iterator.Create();

        IEnumerator<Object> IEnumerable<Object>.GetEnumerator() => this.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();
    }

    public static IteratorEnumerable List()
    {
        return new IteratorEnumerable();
    }

    public static IScriptObject Create(ObjectHandle handle)
    {
        return new Object(handle);
    }

    public void SetAttach(Player player)
    {
        ScriptFunctions.ObjectFunctions.SetAttach(this, player);
    }

    public Player GetAttach()
    {
        return ScriptFunctions.ObjectFunctions.GetAttach(this);
    }

    public void SetRoom(Room unnamed0)
    {
        ScriptFunctions.ObjectFunctions.SetRoom(this, unnamed0);
    }

    public Room GetRoom()
    {
        return ScriptFunctions.ObjectFunctions.GetRoom(this);
    }

    public int GetIndex()
    {
        return ScriptFunctions.ObjectFunctions.GetIndex(this);
    }

    public Entity GetEntity()
    {
        return ScriptFunctions.ObjectFunctions.GetEntity(this);
    }

    public Entity GetModel()
    {
        return ScriptFunctions.ObjectFunctions.GetModel(this);
    }

    public void SetMovement(float speed, float maxdistance)
    {
        ScriptFunctions.ObjectFunctions.SetMovement(this, speed, maxdistance);
    }

    public void SetTexture(int textureid)
    {
        ScriptFunctions.ObjectFunctions.SetTexture(this, textureid);
    }

    public void SetTouchable(bool val)
    {
        ScriptFunctions.ObjectFunctions.SetTouchable(this, val);
    }

    public void SetClickCallback(ref IntPtr callback)
    {
        ScriptFunctions.ObjectFunctions.SetClickCallback(this, callback);
    }

    public void Remove()
    {
        ScriptFunctions.ObjectFunctions.Remove(this);
    }
}
