// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

public struct Room(ObjectHandle handle) : IScriptObject
{
    public ObjectHandle Handle { get; } = handle;

    public struct Iterator(IteratorOpaque opaque) : IEnumerator<Room>
    {
        private IteratorOpaque _opaque = opaque;
        private Room? _current;
        public Room Current => this._current!.Value;
        object IEnumerator.Current => this._current!.Value;

        public static Iterator Create()
        {
            return new Iterator(IteratorOpaque.Create("::RoomIterator ccb::Room::create_iterator()"));
        }

        public bool MoveNext()
        {
            if (this._opaque.IsNull("bool ccb::Room::iterator_is_null(::RoomIterator& in iterator)"))
            {
                this._current = null;
                return false;
            }

            this._current = this._opaque.Get<Room>("::Room ccb::Room::iterator_get(::RoomIterator& in iterator)");
            this._opaque.Advance("void ccb::Room::iterator_advance(::RoomIterator& in iterator)");

            return true;
        }

        public void Reset()
        {
            throw new NotSupportedException();
        }

        public void Dispose()
        {
        }
    }

    public class IteratorEnumerable : IEnumerable<Room>
    {
        public Iterator GetEnumerator() => Iterator.Create();

        IEnumerator<Room> IEnumerable<Room>.GetEnumerator() => this.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();
    }

    public static IteratorEnumerable List()
    {
        return new IteratorEnumerable();
    }

    public static IScriptObject Create(ObjectHandle handle)
    {
        return new Room(handle);
    }

    public string GetName()
    {
        return ScriptFunctions.RoomFunctions.GetName(this);
    }

    public int GetIndex()
    {
        return ScriptFunctions.RoomFunctions.GetIndex(this);
    }

    public int GetIdentifier()
    {
        return ScriptFunctions.RoomFunctions.GetIdentifier(this);
    }

    public Entity GetEntity()
    {
        return ScriptFunctions.RoomFunctions.GetEntity(this);
    }

    public Entity GetObject(int index)
    {
        return ScriptFunctions.RoomFunctions.GetObject(this, index);
    }

    public Entity GetLever(int index)
    {
        return ScriptFunctions.RoomFunctions.GetLever(this, index);
    }

    public bool IsAdjacent(Room unnamed0)
    {
        return ScriptFunctions.RoomFunctions.IsAdjacent(this, unnamed0);
    }

    public Room GetAdjacentRoom(int index)
    {
        return ScriptFunctions.RoomFunctions.GetAdjacentRoom(this, index);
    }

    public Door GetAdjacentDoor(int index)
    {
        return ScriptFunctions.RoomFunctions.GetAdjacentDoor(this, index);
    }

    public Door GetDoor(int unnamed0)
    {
        return ScriptFunctions.RoomFunctions.GetDoor(this, unnamed0);
    }

    public bool IsInside(Entity unnamed0)
    {
        return ScriptFunctions.RoomFunctions.IsInside(this, unnamed0);
    }
}
