// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

public struct Sound(ObjectHandle handle) : IScriptObject
{
    public ObjectHandle Handle { get; } = handle;

    public struct Iterator(IteratorOpaque opaque) : IEnumerator<Sound>
    {
        private IteratorOpaque _opaque = opaque;
        private Sound? _current;
        public Sound Current => this._current!.Value;
        object IEnumerator.Current => this._current!.Value;

        public static Iterator Create()
        {
            return new Iterator(IteratorOpaque.Create("::SoundIterator ccb::Sound::create_iterator()"));
        }

        public bool MoveNext()
        {
            if (this._opaque.IsNull("bool ccb::Sound::iterator_is_null(::SoundIterator& in iterator)"))
            {
                this._current = null;
                return false;
            }

            this._current = this._opaque.Get<Sound>("::Sound ccb::Sound::iterator_get(::SoundIterator& in iterator)");
            this._opaque.Advance("void ccb::Sound::iterator_advance(::SoundIterator& in iterator)");

            return true;
        }

        public void Reset()
        {
            throw new NotSupportedException();
        }

        public void Dispose()
        {
        }
    }

    public class IteratorEnumerable : IEnumerable<Sound>
    {
        public Iterator GetEnumerator() => Iterator.Create();

        IEnumerator<Sound> IEnumerable<Sound>.GetEnumerator() => this.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();
    }

    public static IteratorEnumerable List()
    {
        return new IteratorEnumerable();
    }

    public static IScriptObject Create(ObjectHandle handle)
    {
        return new Sound(handle);
    }

    public void SetVolume(float vol)
    {
        ScriptFunctions.SoundFunctions.SetVolume(this, vol);
    }

    public void Seek(float time)
    {
        ScriptFunctions.SoundFunctions.Seek(this, time);
    }

    public void Stop()
    {
        ScriptFunctions.SoundFunctions.Stop(this);
    }
}
