// <auto-generated/>
namespace CCB.Internal;

using System;
using System.Runtime.InteropServices;
using System.Collections;

public struct Waypoint(ObjectHandle handle) : IScriptObject
{
    public ObjectHandle Handle { get; } = handle;

    public struct Iterator(IteratorOpaque opaque) : IEnumerator<Waypoint>
    {
        private IteratorOpaque _opaque = opaque;
        private Waypoint? _current;
        public Waypoint Current => this._current!.Value;
        object IEnumerator.Current => this._current!.Value;

        public static Iterator Create()
        {
            return new Iterator(IteratorOpaque.Create("::WaypointIterator ccb::Waypoint::create_iterator()"));
        }

        public bool MoveNext()
        {
            if (this._opaque.IsNull("bool ccb::Waypoint::iterator_is_null(::WaypointIterator& in iterator)"))
            {
                this._current = null;
                return false;
            }

            this._current = this._opaque.Get<Waypoint>("::Waypoint ccb::Waypoint::iterator_get(::WaypointIterator& in iterator)");
            this._opaque.Advance("void ccb::Waypoint::iterator_advance(::WaypointIterator& in iterator)");

            return true;
        }

        public void Reset()
        {
            throw new NotSupportedException();
        }

        public void Dispose()
        {
        }
    }

    public class IteratorEnumerable : IEnumerable<Waypoint>
    {
        public Iterator GetEnumerator() => Iterator.Create();

        IEnumerator<Waypoint> IEnumerable<Waypoint>.GetEnumerator() => this.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();
    }

    public static IteratorEnumerable List()
    {
        return new IteratorEnumerable();
    }

    public static IScriptObject Create(ObjectHandle handle)
    {
        return new Waypoint(handle);
    }

    public Entity GetEntity()
    {
        return ScriptFunctions.WaypointFunctions.GetEntity(this);
    }

    public Door GetDoor()
    {
        return ScriptFunctions.WaypointFunctions.GetDoor(this);
    }

    public Room GetRoom()
    {
        return ScriptFunctions.WaypointFunctions.GetRoom(this);
    }
}
