void ServerUpdate();
bool ServerConsole(string command);
void ServerRestart();
void WorldLoaded();
void WorldUpdate();
void PlayerUpdate(Player player);
void PlayerConnect(Player player);
void PlayerDisconnect(Player player);
bool PlayerChat(Player player, string text);
void PlayerAttachesUpdate(Player player);
bool PlayerTakeItem(Player player, Items item);
bool PlayerDropItem(Player player, Items item);
void PlayerDialogAction(Player player, int index, bool response, string input, int selecteditem);
bool PlayerShootPlayer(Player shooter, Player dest, float x, float y, float z, float damage, bool headshot);
bool PlayerShoot(Player player, Items item, int weaponattach);
void PlayerPressPlayer(Player src, Player dest);
bool PlayerConsole(Player player, string input);
void PlayerDeath(Player player, Corpse corpse);
void PlayerRespawn(Player player);
void PlayerHitPlayer(Player src, Player dest, int mousedata, float distance);
bool PlayerExploreCorpse(Player player, Corpse corpse);
void PlayerClickObject(Player player, Object object);
void PlayerShootObject(Player player, Object object);
bool PlayerUseDoorButton(Player player, Door door, Items useditem);
bool PlayerUseItem(Player player, Items item);
bool PlayerSelectItem(Player player, Items item);
void PlayerUse914(Player player, int fineid);
void PlayerClickGui(Player player, GUIElement element);
bool PlayerVoice(Player player, int bank, bool radio);
void PlayerTeleportElevator(Player player, Room room, Entity firstentity, Entity secondentity, float offsetx, float offsety);
void PlayerShootNPC(Player player, NPC npc);
void PlayerKeyAction(Player player, int newmask, int prevmask);
bool PlayerSpectateAction(Player player, Player target, int mode);
void IncomingConnection(Connection conn);
bool ConnectionLoaded(Connection conn);
void ConnectionClosed(Connection conn);
bool ShellDamagePlayer(Shell shell, Player player, float damage);
bool ShellExplode(Shell shell);
void OnLog(string message);
bool FineItem(Items item, int settings, float x, float y, float z);
void CreateItem(Items item);
void RemoveItem(Items item);
void CreateNPC(NPC npc);
void RemoveNPC(NPC npc);
void CreateCorpse(Corpse corpse);
void RemoveCorpse(Corpse corpse);
void CreateObject(Object obj);
void RemoveObject(Object obj);
void CreateLight(Light light);
void RemoveLight(Light light);
void CreateGUIElement(GUIElement element);
void RemoveGUIElement(GUIElement element);
void CreateShell(Shell shell);
void RemoveShell(Shell shell);