<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CCB.Generator\CCB.Generator.csproj" />
      <ProjectReference Include="..\CCB.Syntax\CCB.Syntax.csproj" />
      <ProjectReference Include="..\CCB\CCB.csproj" />
    </ItemGroup>

</Project>
