void OnInitialize();
void OnTerminate();
void ServerUpdate();
bool ServerConsole(string command);
void ServerRestart();
void WorldLoaded();
void WorldUpdate();
void PlayerUpdate(Player player);
void PlayerConnect(Player player);
void PlayerDisconnect(Player player);
bool PlayerChat(Player player, string text);
void PlayerAttachesUpdate(Player player);
bool PlayerTakeItem(Player player, Items item);
bool PlayerDropItem(Player player, Items item);
void PlayerDialogAction(Player player, int index, bool response, string input, int selecteditem);
bool PlayerShootPlayer(Player shooter, Player dest, float x, float y, float z, float damage, bool headshot);
bool PlayerShoot(Player player, Items item, int weaponattach);
void PlayerPressPlayer(Player src, Player dest);
bool PlayerConsole(Player player, string input);
void PlayerDeath(Player player, Corpse corpse);
void PlayerRespawn(Player player);
void PlayerHitPlayer(Player src, Player dest, int mousedata, float distance);
bool PlayerExploreCorpse(Player player, Corpse corpse);
void PlayerClickObject(Player player, Object object);
void PlayerShootObject(Player player, Object object);
bool PlayerUseDoorButton(Player player, Door door, Items useditem);
bool PlayerUseItem(Player player, Items item);
bool PlayerSelectItem(Player player, Items item);
void PlayerUse914(Player player, int fineid);
void PlayerSelectGUI(Player player, GUIElement element);
bool PlayerVoice(Player player, int bank, bool radio);
void PlayerTeleportElevator(Player player, Room room, Entity firstentity, Entity secondentity, float offsetx, float offsety);
void PlayerShootNPC(Player player, NPC npc);
void PlayerKeyAction(Player player, int newmask, int prevmask);
bool PlayerSpectateAction(Player player, Player target, int mode);
void IncomingConnection(Connection conn);
bool ConnectionLoaded(Connection conn);
void ConnectionClosed(Connection conn);
bool ShellDamagePlayer(Shell shell, Player player, float damage);
bool ShellExplode(Shell shell);
void OnLog(string message);
bool FineItem(Items item, int fineid);
void OnCreateItem(Items item);
void OnRemoveItem(Items item);
void OnCreateNPC(NPC npc);
void OnRemoveNPC(NPC npc);
void OnCreateCorpse(Corpse corpse);
void OnRemoveCorpse(Corpse corpse);
void OnCreateObject(Object obj);
void OnRemoveObject(Object obj);
void OnCreateLight(Light light);
void OnRemoveLight(Light light);
void OnCreateGUIElement(GUIElement element);
void OnRemoveGUIElement(GUIElement element);
void OnCreateShell(Shell shell);
void OnRemoveShell(Shell shell);