<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>CCB</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\SourceGenerators\CCB.AstGenerator\CCB.AstGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

</Project>